### ISSUE TITLE
VCH Create wizard misbehaves on vSphere 6.5u1

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#105]
Details to be provided

**Comment by stuclem** [comment]
@alextopuzov has set up a VC with an external PSC for use as the docs test bed, and we are seeing the same problem as @jooskim, in which the selector for compute resources is never populated. @lgayatri is also investigating in this problem.

**Comment by jooskim** [comment]
My initial impression is this is a bug introduced by 6.5. Will tackle this as soon as we are feature completed.
