### ISSUE TITLE
Handle other HTTP response codes while checking vic-machine-server endpoint

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#112]
Currently we only cover HTTP response status of 0. However, the Angular service code should be able to determine other known status codes such as 404, 500 and so on. Without this logic, calling `/container/hello` which Zach Shepherd is working on in a separate PR will cause an unhandled exception.

**Comment by jooskim** [comment]
![image](https://user-images.githubusercontent.com/3834071/33148150-447bcc7a-cf90-11e7-8e62-1e33cda7e39b.png)

**Comment by zjs** [comment]
This should be fixed for 1.3 unless it becomes risky.
