### ISSUE TITLE
vic-ui-plugin build task in Makefile is making noisy logs

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#12]
Some SDK dependencies were archived using BSD tar which causes GNU version of tar to throw a lot of warnings as seen below:

![image](https://user-images.githubusercontent.com/3834071/32070073-b7c0d07c-ba50-11e7-9c21-eb6e8c978826.png)

These warnings should be suppressed.

**Comment by jak-atx** [comment]
This suppression code was originally removed because it would not run locally for me on Mac OS. Closing for now as this doesn't cause any problems.
