### ISSUE TITLE
Create VCH fails with "VIC appliance VM was not found or unreachable. Please make sure you have deployed it correctly."

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-ui#122]
@lgayatri commented on [Thu Nov 23 2017](https://github.com/vmware/vic-product/issues/1135)

@jooskim 
VIC 1.3 - vic-dev-2419-v1.3.0-dev1-178-gfbdb6d5.ova
VCSA: 6.5U1

![image](https://user-images.githubusercontent.com/25006749/33164525-37977d78-d059-11e7-8c11-ca762265e78c.png)

My inventory looks like : 
![image](https://user-images.githubusercontent.com/25006749/33165200-e9bce338-d05b-11e7-8e64-1611df93d7df.png)

Please feel free to SSH to VCSA 10.133.146.15 - root/Admin!23

---

@stuclem commented on [Thu Nov 23 2017](https://github.com/vmware/vic-product/issues/1135#issuecomment-346566395)

I just successfully created a VCH by using the wizard on the VC that @jooskim set up for me, that includes the fix for https://github.com/vmware/vic-ui/issues/105, which is in PR https://github.com/vmware/vic-ui/pull/114 (not merged yet). 

---

@lgayatri commented on [Thu Nov 23 2017](https://github.com/vmware/vic-product/issues/1135#issuecomment-346566925)

Once the latest build is available, I will retry this to confirm.

---

@lgayatri commented on [Fri Nov 24 2017](https://github.com/vmware/vic-product/issues/1135#issuecomment-346756275)

@jooskim mentioned that the related code got merged last evening. Hope to get my hands on new build soon.

---

@stuclem commented on [Mon Nov 27 2017](https://github.com/vmware/vic-product/issues/1135#issuecomment-347201801)

I just deployed OVA build 2603, VIC bundle 15115, and I'm still seeing the same issue with the compute resources selector spinning endlessly:

![spinningaround](https://user-images.githubusercontent.com/16718369/33273458-a96fba96-d38d-11e7-98e6-2d936385745a.jpg)

---

@stuclem commented on [Mon Nov 27 2017](https://github.com/vmware/vic-product/issues/1135#issuecomment-347211090)

When I cancel the VCH deployment, I see the following:

![certerror](https://user-images.githubusercontent.com/16718369/33272195-bd3887aa-d389-11e7-8fe7-27f4a8e9b31c.jpg)

If I click the `FIX` button, I fail to connect:

![fixbutton](https://user-images.githubusercontent.com/16718369/33273394-7164f184-d38d-11e7-8391-9d7d588774fe.jpg)

**Comment by andrewtchin** [comment]
@jooskim @jak-atx please triage and see if we need to pull this in for 1.3

**Comment by jooskim** [comment]
The build used in this ticket is obsolete and all the issues were resolved as of RC2. Closing the issue

**Comment by lgayatri** [comment]
I verified on Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova and the wizard went past without this error. However I filed https://github.com/vmware/vic-ui/issues/191 for the compute screen to list all available datacenters
