### ISSUE TITLE
VCH UI doc link points to 1.1 docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#123]
@cristianfalcone I just noticed that the link to **VIEW NETWORK REQUIREMENTS** points to the 1.1 docs:

![11docs](https://user-images.githubusercontent.com/16718369/33328536-8aa6ca82-d45a-11e7-96c0-e884492a603a.jpg)

Please can you update this to https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_networking.html

Thanks!

**Comment by stuclem** [comment]
Actually, do we really need this great big link? The page that I would propose for the ? is the same as the one for this link, and no other page has a second link.

**Comment by zjs** [comment]
We should fix this for 1.3.0.
