### ISSUE TITLE
Cannot select VM Network for public network in VCH deployment UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#124]
When you deploy a VCH from the command line, if you don't specify `--public-network`, it defaults to the VM Network. But, in the UI, the only networks that you can select are port groups. Until now, whenever I have deployed VCHs with the CLI, I have always used the default VM Network as the public network and the resulting VCHs got their IP addresses from DHCP. In the UI, I have to select a port group, and my VCHs do not get IP addresses.

I am sure that there is some config that I can do on the port group that I assign to the public network, but I am wondering why the CLI default of VM Network is not permitted in the UI. Thanks!

**Comment by jooskim** [comment]
Could be linked to https://github.com/vmware/vic-ui/issues/73 such that a new Java endpoint would retrieve not only port groups but default VM Network

**Comment by hickeng** [comment]
Is `VM Network` a Distributed Port Group? If it's not and there's more than one host then it really isn't a good idea to chose it as it will prevent vMotion of the endpointVM.

**Comment by stuclem** [comment]
@hickeng good point. However, in that case, should we remove VM Network as the default for `--public-network`, and by extension, the default for `--management-network` and `--client-network`? Having the VM Network be the default makes lazy people like me use it rather than go to the trouble of creating PGs...

This isn't really a question for the `vic-ui` repo...

**Comment by jak-atx** [comment]
@stuclem @hickeng is this still a valid issue?

**Comment by stuclem** [comment]
@jak-atx, I think yes. Not being able to select a network rather than a DPG is a deviation between the wizard and the CLI, and it is especially glaring since the CLI uses VM Network for the public network if you don't specify `--public-network`. Even if using VM Network for `--public-network` isn't advisable, I get the impression that a lot of users do exactly that, because it's the easiest option. I remember that @sflxn complained about this in another issue.

So, IMHO, either we should change the UI to allow you to use VM Network for the public network, or we should change the CLI so that it doesn't default to VM Network and forces you to specify a DPG. Obviously, you should take @hickeng 's opinon on this over mine.

**Comment by hickeng** [comment]
@jak-atx I think it's still valid - I'm wondering if there's some magic about `VM Network` that makes it work even when it's not a distributed port group.
I'm honestly somewhat surprised though - I thought the validation required a DPG and that would occur irrespective of whether it was a default value or not.
>> Having checked the code we allow a non-DPG for the endpointVM public/client/management networks, but with the restriction that it will pin the endpointVM to the host in question.
I remain unaware if there's something special about the `VM Network` that would allow vMotion to work across hosts for VMs attached to it without user selection of the mapping, changing IPs or it being a DPG.

**Comment by stuclem** [comment]
Coming back to this one following a related conversation with @dbarkelew. I have opened https://github.com/vmware/vic-product/issues/1613 to discourage use of VM Network for public, and encourage the use of a DPG. @hickeng if you are happy with that, then we can probably close this one.

**Comment by zjs** [comment]
Closing based on vmware/vic-product#1613; using VM Network within VC probably doesn't make sense. We should just have UI users create a DPG.
