### ISSUE TITLE
Some textual cleanup in the VCH delete confirmation modal

### ISSUE THREAD

**Issue by jzt** [vmware/vic-ui#126]
The first and most major is a grammatical mix-up:

Current:
`All this containers VMs will be deleted.`

Proposed:
`All of these container VMs will be deleted.`

The second is slightly more subtle. Specifically, it may be worth considering putting the VCH name in quotes rather than using the comma-enclosed format in the current build. This is especially relevant given the language, considering that the default VCH name is `virtual-container-host`. This leads to a sort of word salad when reading the delete confirmation:

Current:
`The virtual container host, virtual-container-host, manages 0 container VMs (0 stopped and 0 suspended).`

Proposed:
`The virtual container host "virtual-container-host" manages 0 container VMs (0 stopped and 0 suspended).`

Current:
`Delete virtual container host, virtual-container-host and all associated persisted and anonymous volumes?`

Proposed:
`Delete virtual container host "virtual-container-host" and all associated persisted and anonymous volumes?`

**Comment by mdubya66** [comment]
@mhagen-vmware we should take these in. especially this -> of these.

**Comment by zjs** [comment]
Unless the fix becomes risky or complex, it should be included in 1.3.0. However, we should not hold the release for this.
