### ISSUE TITLE
Some rows of the VCH List have a status of "GRAY"

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#127]
**VIC version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

vSphere Client version 6.5.0.10000

**Steps to reproduce:**

Unsure. (For me, simply load the Virtual Container Hosts list.)

**Actual behavior:**

A status of "GRAY" is displayed for some rows.

**Expected behavior:**

Some sort of icon is displayed.

**Additional details as necessary:**

![image](https://user-images.githubusercontent.com/408880/33348664-123a6288-d44c-11e7-9b09-52161994afd2.png)

**Comment by zjs** [comment]
It seems like there's at least one case missing from this logic:

https://github.com/vmware/vic-ui/blob/85ee011a3a36cd0984cd723864fdab01b738176a/h5c/vic/src/vic-webapp/src/app/vch-view/vch-view.template.html#L82-L86

As a part of this issue, we should confirm there aren't additional missing cases.

**Comment by cristianfalcone** [comment]
@lweitzman Which Clarity icon should we use for a 'GRAY' status?

**Comment by zjs** [comment]
This is a low priority, but should be fixed for 1.3.0 if it is easy/low-risk and does not come at the cost of higher priority work.

**Comment by sgairo** [comment]
would unknown icon or ellipses horizontal icon work for gray?

**Comment by cristianfalcone** [comment]
I can set "unknown-status" as a default icon in a PR for now, and change it easily if we need to.

<img width="1277" alt="screen shot 2017-11-30 at 14 30 12" src="https://user-images.githubusercontent.com/3504239/33445334-5466fe56-d5db-11e7-8cfe-b1ca6fc5c048.png">
