### ISSUE TITLE
The "New Virtual Container Host" button is shown only to users in the Administrators group

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#129]
**VIC version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

vSphere Client version 6.5.0.10000

**Actual behavior:**

Only users in the "Administrators" group are able to launch the VCH creation wizard.

**Expected behavior:**

Any user who could successfully create a VCH should be able to launch the VCH creation wizard. We should build off of vSphere's role- and permissions-based access control, instead of assuming that users in a specific group are the ones who should be able to perform a given operations.

In other words, we should look at the actual operations a user can perform, not the name of the group they are in.

Some companies may not use the "Administrator" group. In such an environment, no one would be able to use the wizard. (And worse: because we don't show the button in a disabled state with help text summarizing the issue, and instead hide it completely, they may not understand what the problem is.)

If evaluating whether a user could successfully create a VCH is hard, which it likely is, we can explore alternative heuristics for estimating who can create a VCH. In the short term, it may even be better to show the wizard to all users, and have the operation fail with the appropriate "permission denied" error if they lack necessary permissions.

**Additional details as necessary:**

Relevant code:

https://github.com/vmware/vic-ui/blob/e20eac76e585a86d779e6834fd341ae796c68ee3/h5c/vic-service/src/main/java/com/vmware/vic/PropFetcher.java#L145-L181

cc @stuclem, @pdaigle 

For now, we may want to simply document the requirements for accessing the wizard.

**Comment by jooskim** [comment]
After talking with @zjs and @pdaigle we came to a conclusion for the initial 1.3 release we would not control the visibility of the "New Virtual Container Host" button based on the logged in user's group.

**Comment by zjs** [comment]
As noted above (https://github.com/vmware/vic-ui/issues/129#issuecomment-347940121), we should open up access to all users for 1.3.0, since permissions are still enforced by vSphere.

This change should be kept as small as possible.

This change should be tested with a variety of users with insufficient permissions, including some that have some required permissions, but not others to ensure we're not failing in an unexpected way. Any issues discovered during this testing should be clearly documented in the PR and we should consider a release note for such issues.

An issue referencing this one should be opened to track post-1.3 work.
