### ISSUE TITLE
Signpost text will not display in Firefox 

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#131]
#For bug reports, please include the information below:

**VIC version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

Firefox 56.0 (64-bit) on Ubuntu. (This works on Chrome 62 on the same machine.)

**Steps to reproduce:**

Click on signpost text.

**Actual behavior:**

A Javascript error is printed to the developer console, if open.

**Expected behavior:**

The signpost text is displayed.

**Additional details as necessary:**

![image](https://user-images.githubusercontent.com/408880/33350684-f59b4c60-d454-11e7-8ef5-15d4bae4754f.png)

**Comment by cristianfalcone** [comment]
This is a Clarity Signpost component bug resolved in version 0.10.5 (https://github.com/vmware/clarity/issues/1306). We need to update Clarity (currently version 0.10.4 is being used for VIC).

**Comment by zjs** [comment]
We should summarize the risks and benefits of this Clarity upgrade, explain them to @mhagen-vmware and @mlh78750, and get their feedback on whether this should be included in 1.3.0.

**Comment by mlh78750** [comment]
Confirm for me: Is the downside leaving it the way it is just limited to signposts not working on firefox? or is there other issues we will hit related to this?

**Comment by cristianfalcone** [comment]
Till now, I did not found another Clarity related issue other than the signposts in Firefox. What we can do is update to Clarity 0.10.5 to minimize impact. The update includes 3 bug fixes only. Already tested it, and signposts work fine in Firefox with version 0.10.5.
