### ISSUE TITLE
Create VCH wizard says "VM endpoint" instead of "Endpoint VM"

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#140]
In the Compute page of the VCH deployment wizard, the text "VM endpoint settings" should be "VCH  endpoint VM settings:

![vmendpoint](https://user-images.githubusercontent.com/16718369/33384529-8c09e95a-d526-11e7-83f6-88b61eb92fd7.jpg)

**Comment by zjs** [comment]
This is a very low priority, but could be included in the release if it is a simple text change that can be made without sacrificing something else.
