### ISSUE TITLE
On my system, the compute resource selection widget does not include hosts

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#148]
On the second page of the VCH Creation Wizard, I would expect hosts to be displayed as children of the cluster, but they are not:
![image](https://user-images.githubusercontent.com/408880/33407933-69171948-d528-11e7-94ed-0c67af8e3f55.png)

These hosts appear, as expected, in the Hosts & Clusters tree:
![image](https://user-images.githubusercontent.com/408880/33407937-73a3d78e-d528-11e7-9e14-c88a811b2d69.png)

Let me know if there's any diagnostic or log information I could collect to aid in debugging.

**Comment by jooskim** [comment]
This is a legit issue I can reproduce. Setting it to high priority

**Comment by jak-atx** [comment]
@mhagen-vmware we were able to reproduce this so we think it should go into 1.3. let us know if you think otherwise.

**Comment by jooskim** [comment]
After upgrading to Clarity 0.10.x the syntax and usage have changed, essentially rendering the tree node in an invalid state.
