### ISSUE TITLE
VCH Wizard. Security tab. Meaning of  "Enable secure access to this VCH" is unclear

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic-ui#161]
**VIC version:**
vic-v1.3.0-rc2-2628-9e2a95b6.ova
**Deployment details:**
Nimbus deployment, no VCH
**Steps to reproduce:**
Run the Wizard 
**Actual behavior:**
In the Security tab, when the slider labelled: "Enable secure access to this VCH" is off the wizard implicitly performs following configuration choices:
- no client certificates
- self signed server certificates
- disables the ability to configure security for registries

There should be a clear description of these configuration choices, the current message reflects only the disabling of client certificates which is incomplete and should instead apply to the other slider on the tab, the one labelled with: "Client Certificates"

**Expected behavior:**
The first problem is the label itself. It should say something like: "Configure secure access to the VCH". The second problem is the description and warning message which should be applied to the other slider button the one labelled: "Client Certificates". The warning message for the main slider should point out the three configuration options described above. The warning message can be displayed only with the slider is off, rather than on the main page.

**Comment by mdubya66** [comment]
If we have a PR merged by Jan 17 then we can take this fix for 1.3.1

**Comment by jak-atx** [comment]
This is addressed by #296 closing as duplicate.
