### ISSUE TITLE
VC name may not work for --target in VCH wizard

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic-ui#181]
**VIC version:**
vic 1.3 rc2

**Deployment details:**
Name of VC is: localhost.localdom.eng.vmware.com (not a valid DNS name)

**Steps to reproduce:**
Use the wizard to create the VCH

**Actual behavior:**
The VCH creation fails with: 
_Error creating VCH_ 

**Expected behavior:**
VCH should succeed then wizard should be able to use the IP address of VC as target.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic #6918](https://github.com/vmware/vic/issues/6918) via [**ZenHub**](https://www.zenhub.com/)
