### ISSUE TITLE
VCH creation in Wizard fails with non-descriptive message

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic-ui#182]
**VIC version:**
vic 1.3 rc2

**Deployment details:**
Name of VC is: localhost.localdom.eng.vmware.com (not a valid DNS name)

**Actual behavior:**
VCH creation fails with non-descriptive message:
_VCH creation failed_

**Expected behavior:**
The error message should be more descriptive.

**Comment by jak-atx** [comment]
@AngieCris do you know if we are sending a message to the ui for this error or if there is a log for this particular error that we can point the user to in case of this failure?

**Comment by jak-atx** [comment]
I think we had actually fixed this issue with not showing error messages with our RC3 fixes. The closest I can get to reproduce it mismatched thumbprint. Which does show an error message and the UI does display it: {"message":"Validation Error: Failed to connect to localhost.localdom.eng.vmware.com: Post https://localhost.localdom.eng.vmware.com/sdk: Host \"localhost.localdom.eng.vmware.com:443\" thumbprint does not match \"8A:FD:1E:AF:EC:D3:31:46:FB:E3:9E:89:86:4D:D1:20:03:95:A2:F4\""}

@lcastellano as soon as RC3 is available please re-test this and let me know if you see a more descriptive error message.

**Comment by AngieCris** [comment]
@jak-atx I'm not sure how UI uses the JSON response from the API. For any creation failure, there should be a JSON response from the API with descriptive response body

**Comment by jak-atx** [comment]
@AngieCris yes, I believe that we didn't display it in RC2 but fixed this in RC3

**Comment by jak-atx** [comment]
Addressed in https://github.com/vmware/vic-ui/pull/99
