### ISSUE TITLE
UI plugin installer slow

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-ui#184]
@gigawhitlocks commented on [Tue Dec 05 2017](https://github.com/vmware/vic-product/issues/1226)

Timestamps:
```
Dec  5 2017 18:22:16.417Z INFO  Found 1 VM(s) tagged as OVA
Dec  5 2017 18:37:24.078Z INFO  Attempting to configure ManagedByInfo
Dec  5 2017 18:37:24.263Z INFO  Successfully configured ManagedByInfo
```

15 minutes on this step? D:
![](https://i.imgflip.com/20jqey.jpg)

---

@gigawhitlocks commented on [Tue Dec 05 2017](https://github.com/vmware/vic-product/issues/1226#issuecomment-349411156)

```log.Infof("Found %d VM(s) tagged as OVA", len(vms))
for i, v := range vms {
        log.Debugf("Checking IP for %s", v.Reference().Value)
        vmIP, err := v.WaitForIP(ctx)
        if err != nil && i == len(vms)-1 {
                return nil, errors.Errorf("failed to get VM IP: %s", err)
        }

        // verify the tagged vm has the IP we expect
        if vmIP == ip {
                log.Debugf("Found OVA with matching IP: %s", ip)
                return v, nil
        }
}

return nil, errors.Errorf("no VM(s) found with OVA tag")
```

seems to be related to this piece of code

---

@gigawhitlocks commented on [Tue Dec 05 2017](https://github.com/vmware/vic-product/issues/1226#issuecomment-349411449)

I am currently doing a reinstall of the UI plugin and the step listed above has exceeded 30 minutes of waiting.

**Comment by gigawhitlocks** [comment]
To reproduce the bug above, the OVA needs to be installed using a FQDN to refer to the OVA during install time. This bug is thus related https://github.com/vmware/vic-product/issues/1215 . Installing without an FQDN for the OVA does not seem to produce this bug.

After install, the hack that @morris-jason put in place in that issue will be necessary to reproduce this, I believe.

**Comment by jak-atx** [comment]
Closing as fixed in https://github.com/vmware/vic-product/issues/1215 and this issue has not been re-reported.
