### ISSUE TITLE
Accepting certificate doesn't allow vic-machine-server API to be accessed

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-ui#186]
I have installed the VIC UI plugin in vSphere and when I navigate to that page I am presented with an error:
![screenshot at 2017-12-05 16-48-51](https://user-images.githubusercontent.com/3743903/33635086-36d42f58-d9dc-11e7-87ef-e3e9a315feac.png)

That appears to be normal because I used self-signed certificates during my deployment, so I click Fix and click through the browser screen where I permanently save the certificate to my browser. Then I go back to the vSphere page and try again:

![no-vch-create](https://user-images.githubusercontent.com/3743903/33635128-5b0c5986-d9dc-11e7-9510-56475d6c6d5e.gif)

No dice. No VCH creation ability. :(

**Comment by andrewtchin** [comment]
im assuming firefox 57?

**Comment by gigawhitlocks** [comment]
Yep

**Comment by jooskim** [comment]
@gigawhitlocks Well it's weird because I ran it against Firefox 57 and it worked.  Is it the same instance where it took close to an hour to get the plugin installed?

**Comment by gigawhitlocks** [comment]
@jooskim I have an issue open for that as well, please add details to #184

**Comment by gigawhitlocks** [comment]
Oh and -- no, this is a different instance. On this one I did nothing fancy with certs or FQDNs and did not experience the slowness seen in #184

**Comment by gigawhitlocks** [comment]
This is Firefox 57 on Linux for what it's worth

**Comment by gigawhitlocks** [comment]
@jooskim @jak-atx same issue with the newer ova
![no-vch-2](https://user-images.githubusercontent.com/3743903/33637535-1aef486c-d9e7-11e7-91c0-e8721d94f8c6.gif)

**Comment by gigawhitlocks** [comment]
I lied -- I had forgotten to restart the services. We're all good -- issue does not present in most recent OVA.

**Comment by jooskim** [comment]
Thank you for saving our lives 👍
