### ISSUE TITLE
Plugin throws JS errors in older versions of chrome

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#187]
**Details:**
In chrome versions (<=56) we are seeing a JS/Angular error
![untitled](https://user-images.githubusercontent.com/15793168/33635150-778b1a3e-d9dc-11e7-83e9-574c26ab19b0.jpeg)

This may be due to a known issue in zone.js 0.8.8

**Comment by jooskim** [comment]
Reference: https://github.com/angular/angular-cli/issues/6036

**Comment by jooskim** [comment]
Confirmed the issue is present in a Windows VM running Chrome 54. Also upgrading the zone.js to 0.8.9 from 0.8.8 fixed the problem.

**Comment by mdubya66** [comment]
adding kind note. this needs a release note.

**Comment by mdubya66** [comment]
workaround was to upgrade chrome

**Comment by stuclem** [comment]
Release note:

- <b>Virtual Container Hosts view is empty in versions of Chrome older than version 56. [#187](https://github.com/vmware/vic-ui/issues/187)</b><br>If you go to the Virtual Container Hosts view of the vSphere Integrated Containers plug-in in an older version of Chrome, the VCH list is empty. If you right-click in the browser and select **Inspect**, you see an `UncaughtType error`.  

   Workaround: Upgrade Chrome to a version greater than version 56.

@jooskim is this OK?

**Comment by jooskim** [comment]
This issue has been fixed and I confirmed it works in Chrome version 56. We might not need the release note for this, as it's now impossible to reproduce this issue.

**Comment by stuclem** [comment]
@jooskim shall we leave it there, just in case?
