### ISSUE TITLE
Create VCH wizard lists only one datacenter 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#191]
Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova

![image](https://user-images.githubusercontent.com/25006749/33646579-518959aa-da76-11e7-8d31-1318510920f4.png)

I have two datacenters on this VCSA

![image](https://user-images.githubusercontent.com/25006749/33646612-72d41a82-da76-11e7-8fb7-b7a429eebd2e.png)

The user can choose to create VCH on any datacenter. We need to list the compute accordingly in the UI.
@stuclem

**Comment by jooskim** [comment]
This is all addressed in RC3 or RC4 we're about to tag soon. I'll reach out to you once you can test one

**Comment by jak-atx** [comment]
Addressed in https://github.com/vmware/vic-ui/pull/172
