### ISSUE TITLE
Create VCH wizard throws invisible exception on Finish

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#192]
Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova 

![image](https://user-images.githubusercontent.com/25006749/33648229-dea48578-da7e-11e7-8323-061e6e097390.png)

I checked in vsphere-ui logs and logs in /storage/log/ of OVA but could not figure out where these logs would go. Please let me know what logs to upload.

**Comment by lgayatri** [comment]
I have collected logs, but cant attach due to size restriction

**Comment by jak-atx** [comment]
This should be fixed in RC3. Need to verify.

**Comment by mlh78750** [comment]
@jak-atx pointer to dup or the PR with the fix?

**Comment by jak-atx** [comment]
@mlh78750 https://github.com/vmware/vic-ui/pull/99
