### ISSUE TITLE
If there is XSRF-TOKEN cookie set up, it might prevent the UI from reaching API endpoint

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#195]
Any version since RC2 is potentially subject to this issue.

**Steps to reproduce:**
First, create a cookie named `XSRF-TOKEN` (use Chrome plugin called EditThisCookie to set one)  while logged into the vSphere Client session. Then follow the :

1. Deploy OVA
2. Install the VIC UI H5 Client plugin
3. Log into H5 Client
4. Create a cookie named `XSRF-TOKEN` (use Chrome plugin called EditThisCookie to set one) 
5. In H5 Client, go to `vSphere Integrated Containers` -> `Summary` or any other tab.
6. Make sure the warning about self-signed certificate shows up
7. Click the link that opens up a tab to accept the self-signed certificate
8. Once accepting the certificate, come back to the H5 Client and click 'Refresh'

**Actual behavior:**
The Clarity alert would not go away

**Expected behavior:**
The Clarity alert should be dismissed

**Additional details as necessary:**
Angular's HttpClient intercepts the HTTP call and if it finds a cookie named `XSRF-TOKEN` it would include it in the request header. For some reason, this cookie was set up in a VC setup when I logged into it using FQDN but not there when logged using the IP address.

ref. https://stormpath.com/blog/angular-xsrf

**Comment by jooskim** [comment]
Workaround is to remove the XSRF-TOKEN and try clicking the refresh button:

![image](https://user-images.githubusercontent.com/3834071/33683701-6bd3e6f2-da91-11e7-8842-ef5dafd825d9.png)

![image](https://user-images.githubusercontent.com/3834071/33683721-84b087de-da91-11e7-9fa5-53cd09367b9b.png)

**Comment by jak-atx** [comment]
We need to dig into this a bit to investigate exactly under which circumstances we are served that particular cookie (since it doesn't appear to always happen).
