### ISSUE TITLE
Fix broken H5C plugin integration tests with Firefox on Windows

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#20]
A Windows box we set up for integration testing for VIC UI has Selenium Grid 3.5.3 running, which has capabilities for IE 11, Chrome and Firefox. Currently when attempting to run a test on Firefox, the test session would end up logging out immediately after successful login. This is because the Selenium binary version used by the HSUIA project (2.53.0) is trying to call a method that no longer exists on a newer version (3.5.3) used for setting up the node.

**Logs**
```
# org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
# Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
# System info: host: 'MSEDGEWIN10', ip: '10.25.200.225', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
# Driver info: driver.version: RemoteWebDriver
# Command duration or timeout: 17 milliseconds
# Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
# System info: host: '93528c527173', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.7.0_131
```

In order to fix the issue we have to either upgrade the Selenium binary in the HSUIA project, or use a Selenium Node version 2 with a Firefox capability. Neither of which is an easy solution and requires many trials and errors until we can settle on a solution that works best.

Until the issue is addressed, H5C on Firefox tests would remain disabled on our nightly node.

**Comment by jak-atx** [comment]
These tests are being rewritten in protractor so this particular issue is no longer valid. Will verify the portlet tests run under this combination in this issue https://github.com/vmware/vic-ui/issues/298
