### ISSUE TITLE
VCH create integration test case fails if # of VCHs <= 10

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#201]
Currently we have one test case for VCH create wizard where a basic set of configurations is used to deploy a VCH. Per the E2E spec file, once a new VCH is successfully created the Protractor will find the next button in the pagination area of the data grid. However, the pagination element is not visible when there there is only one page to show; that is, the number of VCHs is equal to or less than 10.

**Comment by jak-atx** [comment]
Hmm..I'll take a look. I know this was working fine at one point with either 1 or 2 pages in the datagrid.

**Comment by jooskim** [comment]
I need a little more investigation on this. Seems like it worked when there were 2. It probably has to do with Protractor not finding an element because it was too fast or slow.

**Comment by jak-atx** [comment]
Have not seen this in quite awhile. Closing as non-reproducible.
