### ISSUE TITLE
Show Datacenter list in a tree structure 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#207]
@jooskim 

Build  :  vic-v1.3.0-rc3-2784-7d227d5c.ova

![image](https://user-images.githubusercontent.com/25006749/33764658-62f2b468-dc3b-11e7-9ac6-9a3f22715d32.png)

Instead of showing each datacenter in a separate box here - it will be better to show all of them in a single tree structure which can be expandable upon selection.

**Comment by lgayatri** [comment]
User can have any number of datacenters and representing this way will be of bad user experience.

**Comment by mlh78750** [comment]
If a customer had 15 datacenters would they have 15 of those panels?

**Comment by jak-atx** [comment]
I believe that would be the case currently. We need to fix how the tree is assembled to scale better.

**Comment by jooskim** [comment]
Yes that's a bug. I am aware how this is happening. Some simple CSS should easily fix it. Wonder if we can get this in for RTM. @jak-atx do you know the schedule?

**Comment by jak-atx** [comment]
@jooskim we are still fixing critical issues. If you can get the fix the fix in we can run it by @mhagen-vmware with a cherry pick pr. Either way we can get the fix in to master at least.

**Comment by lgayatri** [comment]
This issue is still not fixed in rc4.

**Comment by lgayatri** [comment]
This issue is fixed in https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc6-3010-f8cc7317.ova.

![image](https://user-images.githubusercontent.com/25006749/34551462-07f2c390-f140-11e7-9f24-301e23c2021f.png)
