### ISSUE TITLE
Expanding VCH shows "Error loading VCH log!" consistently when multiple datacenters exist

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#209]
Build: vic-v1.3.0-rc3-2784-7d227d5c.ova 
![image](https://user-images.githubusercontent.com/25006749/33769545-a08a0834-dc50-11e7-95b3-
815752c4073f.png)

VCSA: wdc-stvc3944-146-dhcp15.eng.vmware.com
administrator@vsphere.local/Admin!23
root/Admin!23

Please access the setup directly.

**Comment by jak-atx** [comment]
<img width="1261" alt="screen shot 2017-12-08 at 10 05 46 am" src="https://user-images.githubusercontent.com/15793168/33774055-9fa980a8-dbff-11e7-8a06-11cf65103f20.png">
This seems to be an issue with how we are handling error display, similar to #202 

But it seems with this particular error it states to select a datastore but there is no user action available to do this.

@lweitzman i think we need to look into individual error cases and see which ones have user actions applicable

**Comment by mlh78750** [comment]
We should audit all the error paths to make sure we're doing a better job with passing back API reported errors the correct way.

**Comment by jak-atx** [comment]
Agreed. Opened https://github.com/vmware/vic-ui/issues/211 to address the error path inconsistencies across the board.

**Comment by zjs** [comment]
> But it seems with this particular error it states to specify a datacenter but there is no user action available or context of how to do this.

This sounds very similar to the error in #208. In a multi-datacenter system, you may need to use the `/target/.../datacenter/.../vch/.../log` endpoint instead of `/target/.../vch/.../log`.

**Comment by lgayatri** [comment]
Hitting https://github.com/vmware/vic-ui/issues/257 now
