### ISSUE TITLE
Get over unsigned SSL certs warning while running integration tests on IE11

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#21]
Running a VIC UI integration test against IE 11 leads to a page warning about the insecure SSL certificate, leading the rest of the test steps to hang and eventually fail. A brief investigation revealed that there does not seem to be a capability that allows bypassing insecure SSL certificates unlike in Firefox. So the only way to get past this screen is to tell Selenium driver to click on the links  in the warning page.

Until the issue is addressed, IE tests would remain disabled on our nightly node.

**Comment by mlh78750** [comment]
In Internet Options->advanced->security uncheck "check for publisher's cert" "check for server ... revocation"  This sets it like that for the entire OS, but I think it will allow IE to work. This is not something I'd recommend on anything other than a test computer.

**Comment by mlh78750** [comment]
Better answer would be to setup the environment with a real cert for the server.

**Comment by jooskim** [comment]
@mlh78750 Thanks for the workaround and the better solution! This Windows box is specifically set up for VIC-UI E2E testing so it should be good for now - I'll test again if I can get past the screen, but eventually setting up a real cert would be a more proper and straightforward solution.

**Comment by jooskim** [comment]
I've tried unticking those options in Internet Options and still IE would complain that the site is not secure. But then I realized I could download root CAs from the VCSA and install them on the test box

ref 1: https://kb.vmware.com/s/article/2108294?language=en_US 
ref 2: https://technet.microsoft.com/en-us/library/cc754841.aspx

I confirm this issue is now resolved.
