### ISSUE TITLE
H5C UI : Implement page navigation for  viewing Containers

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#215]
@mdubya66  @jooskim @mlh78750 

Build: vic-v1.3.0-rc3-2784-7d227d5c.ova
I have about 55 VCHs with 2650+ containers

![image](https://user-images.githubusercontent.com/25006749/33792543-feba766e-dcc8-11e7-8d1b-39dd00a14dd4.png)

Page navigation not available to view the complete container list and list shows as if there are only 10 containers .

![image](https://user-images.githubusercontent.com/25006749/33792547-2cfe97ee-dcc9-11e7-9dd6-d26c4eb40f9a.png)

**Comment by jak-atx** [comment]
cc @mhagen-vmware

**Comment by jooskim** [comment]
Issue was not fixed. Reopening.

**Comment by lgayatri** [comment]
Fixed in https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.1-rc3-3401-132fb13d.ova
