### ISSUE TITLE
ComputeResource tree hangs, fails to load 

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#217]
10.161.2.135, Administrator@vsphere.local, Admin!23

console contains this warning:
getPartsFromVsphereObjectId called with a non "urn:vmomi" objectId: urn:vic:vic:Root:vic%252Fvic-root

network request returns all 200s

![pasted image at 2017_12_11 04_17 pm](https://user-images.githubusercontent.com/15793168/33857393-0f362e4c-de91-11e7-9fcd-e2d8e33edfa8.png)

**Comment by AngieCris** [comment]
Also, when I refresh the browser, these two errors pop up in the console:
![screen shot 2017-12-11 at 5 50 28 pm](https://user-images.githubusercontent.com/6562128/33859928-e2ec061c-de9b-11e7-8189-6f1b17f46ca1.png)
not sure if it's related?

**Comment by jooskim** [comment]
@AngieCris The console error seems unrelated to the VIC UI plugin itself and I cannot make much inference only with the screenshot.

**Comment by jooskim** [comment]
I realized the spinner spinning indefinitely might have to do with the fact that this VC does not have any cluster which hints that the logic that processes available compute resources might be faulty.

**Comment by AngieCris** [comment]
@jooskim I have 1 VC deployed within this datacenter. Should it be listed here under `Compute Resource`?
