### ISSUE TITLE
UI constructs incorrect request body when firewall policy is set on a container network

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#219]
**VIC version:**

v1.3.0-rc3-15260-19211b3

**Deployment details:**

N/A

**Steps to reproduce:**

Using the creation wizard, specify a container network with a firewall setting:

![image](https://user-images.githubusercontent.com/408880/33858501-b0e2147a-de84-11e7-9bd4-114a5fd7391c.png)

**Actual behavior:**

The creation fails with this error:

>  parsing vch body from "" failed, because json: cannot unmarshal array into Go struct field ContainerNetwork.firewall of type string

**Expected behavior:**

Creation succeeds.

**Logs:**

N/A

**Additional details as necessary:**

The cause of this failure is in the way the UI constructs the request body. The firewall setting must be a string, not an array:

```
{
  "name": "firewall-test",
  "compute": {
    "cpu": {
      "limit": {
        "units": "MHz",
        "value": 0
      }
    },
    "memory": {
      "limit": {
        "units": "MiB",
        "value": 0
      }
    },
    "resource": {
      "name": "/dc1/host/cluster1"
    }
  },
  "storage": {
    "image_stores": [
      "sharedVmfs-0"
    ],
    "base_image_size": {
      "units": "GiB",
      "value": 8
    }
  },
  "network": {
    "bridge": {
      "ip_range": "172.16.0.0/12",
      "port_group": {
        "name": "bridge"
      }
    },
    "public": {
      "port_group": {
        "name": "PublicNetwork"
      }
    },
    "container": [
      {
        "port_group": {
          "name": "InternalNetwork"
        },
        "nameservers": [
          "8.8.8.8"
        ],
        "alias": "test",
        "firewall": [                                <---[ Problem here! ]---
          "published"
        ]
      }
    ]
  },
  "auth": {
    "client": {
      "certificate_authorities": []
    },
    "server": {
      "generate": {
        "size": {
          "value": 2048,
          "units": "bit"
        },
        "organization": [
          "firewall-test"
        ],
        "cname": "firewall-test"
      }
    }
  },
  "container": {},
  "debug": 0,
  "endpoint": {
    "operations_credentials": {
      "user": "administrator@vsphere.local",
      "password": "Admin!23"
    }
  },
  "registry": {}
}
```

**Impact:**

Because the firewall policy is always specified when creating a container network, this prevents container networks from being specified in the UI.

**Comment by jooskim** [comment]
Ref: https://github.com/vmware/vic/blob/master/lib/apiservers/service/swagger.json#L601

**Comment by jooskim** [comment]
This is a similar issue to https://github.com/vmware/vic-ui/issues/220
