### ISSUE TITLE
 UI constructs incorrect request body when using static IP addresses

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#220]
**VIC version:**

v1.3.0-rc3-15260-19211b3

**Deployment details:**

N/A

**Steps to reproduce:**

Using the creation wizard, specify a static IP address for the public network:

![image](https://user-images.githubusercontent.com/408880/33859274-f8871dc2-de87-11e7-8d6f-07e53cf17cce.png)

**Actual behavior:**

The creation fails with this error:

>  parsing vch body from "" failed, because json: cannot unmarshal object into Go struct field Network.static of type models.CIDR

**Expected behavior:**

Creation succeeds.

**Logs:**

N/A

**Additional details as necessary:**

The cause of this failure is in the way the UI constructs the request body. The static setting must be a string, not an object:

```
{
  "name": "firewall-test",
  "compute": {
    "cpu": {
      "limit": {
        "units": "MHz",
        "value": 0
      }
    },
    "memory": {
      "limit": {
        "units": "MiB",
        "value": 0
      }
    },
    "resource": {
      "name": "/dc1/host/cluster1"
    }
  },
  "storage": {
    "image_stores": [
      "sharedVmfs-0"
    ],
    "base_image_size": {
      "units": "GiB",
      "value": 8
    }
  },
  "network": {
    "bridge": {
      "ip_range": "172.16.0.0/12",
      "port_group": {
        "name": "bridge"
      }
    },
    "public": {
      "port_group": {
        "name": "PublicNetwork"
      },
      "static": {                                          <---[ Problem here! ]---
        "ip": "192.168.1.22/24"
      },
      "gateway": {
        "address": "192.168.1.1"
      },
      "nameservers": [
        "8.8.8.8"
      ]
    }
  },
  "auth": {
    "client": {
      "certificate_authorities": []
    },
    "server": {
      "generate": {
        "size": {
          "value": 2048,
          "units": "bit"
        },
        "organization": [
          "firewall-test"
        ],
        "cname": "firewall-test"
      }
    }
  },
  "container": {},
  "debug": 0,
  "endpoint": {
    "operations_credentials": {
      "user": "administrator@vsphere.local",
      "password": "Admin!23"
    }
  },
  "registry": {}
}
```

**Impact:**

Because this is a syntax issue in the way the request body is constructed when using a static address, this prevents static addresses from being specified using the UI.

**Comment by jak-atx** [comment]
@zjs can you point us to latest swagger spec?

**Comment by jooskim** [comment]
Think I found it: https://github.com/vmware/vic/blob/master/lib/apiservers/service/swagger.json#L592
https://github.com/vmware/vic/blob/master/lib/apiservers/service/swagger.json#L558

**Comment by jooskim** [comment]
so it should have been `"static": "#.#.#.#/#"`
it should be an easy fix.

**Comment by zjs** [comment]
So far it doesn't make a difference, but for 1.3 fixes you should look at the release branch just to be safe: https://github.com/vmware/vic/blob/releases/1.3.0/lib/apiservers/service/swagger.json

**Comment by jooskim** [comment]
Relevant code from the vic-ui repo would be: https://github.com/vmware/vic-ui/blob/releases/1.3.0/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.component.ts#L339
