### ISSUE TITLE
Old favicon briefly appears when Admiral loads

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-ui#232]
Upon loading or refreshing the Admiral interface, one can briefly see the old Admiral logo appear before it is replaced by the VIC logo. This issue is entirely cosmetic, but this behavior is certainly not desired:
![changing-favicon](https://user-images.githubusercontent.com/3743903/33910266-bdb37a98-df53-11e7-9a12-2d52d6022fce.gif)

**Comment by jak-atx** [comment]
@gigawhitlocks this isn't the vic ui. does admiral have a repo to submit issues to?

**Comment by gigawhitlocks** [comment]
Do they? 😆
