### ISSUE TITLE
Management network options in UI do not match CLI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#233]
Following Slack chat with @zjs

**VIC version:**

`vic-dev-2816-v1.3.0-rc3-2816-236fe98f.ova`

**Deployment details:**

- Deploy VCH from the Create VCH wizard in the vSphere Client
- Enter values for all Management network options, i.e.:
  - Static IP address
  - Gateway
  - Routing destination

     ![mgmtnet](https://user-images.githubusercontent.com/16718369/33930417-21cf2358-dfed-11e7-9b14-85cfb1d621bb.jpg)

- Complete the rest of the wizard.

**Actual behavior:**

In the generated `vic-machine` command at the end of the Create VCH wizard there is a new `--management-network-routing` option, that does not appear in the `vic-machine create` help:

![mgmtroute](https://user-images.githubusercontent.com/16718369/33930582-b160ba5e-dfed-11e7-8e94-de0cbef6b05b.jpg)

The routing destination is also included in the `--management-network-gateway` option, which is the same behaviour as for the client network routing destination and corresponds to the description of `--management-network-gateway` in the `vic-machine create -x` help. Is this deliberate, or is this a bug in the API/UI?

Also, there doesn't seem to be any provision for the  `--asymmetric-routes` option for management networks in the wizard. Is this deliberate?

Finally, it seems to me (at least that is what I was told and what I have documented) that if you specify a static IP address for the management network, it is not always obligatory to specify the gateway: 

"If the management and client networks are L2 adjacent to their gateways, you do not need to specify the corresponding gateways for those networks."

However, in the UI, if you specify a static IP, it seems that you must always also specify the gateway.

**Expected behavior:**

UI options should map to CLI options exactly (or so I understand).

I listed all of these items in the same issue because they seem to me to be related. Let me know if I should break this into separate issues.

**Comment by stuclem** [comment]
Also, in the CLI, you can specify a static network address for the management and client networks as FQDNs. This is not possible in the UI

**Comment by cristianfalcone** [comment]
`--asymmetric-routes` is not an option considered in mockups, neither the API has a way to map that option, currently. We'll need a new ticket for this particular option if it's needed to be implemented in the UI and API.

Regarding net masks and FQDNs for this option we need to check with API guys, since swagger file specifies that this field should be an IP address only. I can add validations easily for CIDRs and FQDNs in that field once we get a confirmation that the API supports them.

@jak-atx @stuclem @zjs
