### ISSUE TITLE
Incorporate ng e2e creation wizard tests into nightly integration jenkins runs

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#235]
Currently we run the nightly integration tests and the ng e2e create tests separately. ng e2e tests are not automated. We need to get those as an additional test step into our integration nightly tests.

**Comment by jooskim** [comment]
The e2e wizard tests are already integrated into a nightly Jenkins run as seen below.

![image](https://user-images.githubusercontent.com/3834071/34420472-5383c49c-ebcf-11e7-9e5f-e7534532f8a2.png)

Do we need to take further steps? If not we can close this issue.

**Comment by jak-atx** [comment]
e2e tests are now part of our nightly jenkins runs.
