### ISSUE TITLE
(UX issue) Incredibly important certificate download link hidden under unassuming context menu

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-ui#237]
The certificate download link for getting the certificates from a VCH is far too hidden, at least until these certs can be provided to Admiral automatically without user intervention.

![screenshot at 2017-12-13 12-54-44](https://user-images.githubusercontent.com/3743903/33956645-d1768942-e004-11e7-8853-5a8bffb66afc.png)

It's really great that this is here at all, but in combination with the truncated output in #236 , if a user uses TLSverify for their VCH (which is the default in the UI installer!) then after the installer completes, there's nothing to tell them that they need to download those certs, nor that they are even there. I only just stumbled across that context menu while trying to discover how to destroy a VCH! This is especially bad because even though this feature is likely documented, the user first has to know that they need the certs to even know where to look in the documentation to see where to download them.. all-in-all, poor discoverability will lead to a rough user experience.

This is compounded by a UX issue in Admiral making it unclear when client certificates are needed by the user. I am working with them on that issue as well.

Expect issues to be filed by users where they cannot figure out how to add a VCH from the UI through Admiral because they are completely unaware that they need the certs hidden in that context menu.

**Comment by jak-atx** [comment]
Cc: @lweitzman

**Comment by AngieCris** [comment]
Cc: @zjs what do you think about this? With the asynchronous portion of creation log not included in API, users might have to dig the doc to find out that they need to download the certs after the creation finishes

**Comment by zjs** [comment]
> The certificate download link for getting the **certificates** from a VCH is far too hidden ...

Note that this only lets you download _one_ certificate: the server certificate. We don't generate client certificates/keys via the UI/API, so we don't allow them to be downloaded. This is discussed in more detail in the design document: vmware/vic#6702

> if a user uses TLSverify for their VCH (which is the default in the UI installer!) then after the installer completes, there's nothing to tell them that they need to download those certs, nor that they are even there.

The user only needs the server certificate if they chose to invoke the docker client with `--tlsverify` (vs. just `--tls`). 

I think the "real" ask here is to help users understand how to use the docker client to connect to the VCH that they created. I think that would be valuable, but I think that needs to include more than just information about certificates.

> This is compounded by a UX issue in Admiral making it unclear when client certificates are needed by the user.

This seems unrelated.

**Comment by gigawhitlocks** [comment]
>The user only needs the server certificate if they chose to invoke the docker client with --tlsverify (vs. just --tls).

This is false -- the user needs the certificates if `vic-machine` was called with `--tls-verify`.
This option is also selected by default in VCH deployment screen and there is a warning dissuading the user from deselecting it:

![screen shot 2017-12-13 at 3 16 57 pm](https://user-images.githubusercontent.com/3743903/33962938-ced72e76-e018-11e7-91f4-9c8a810e482d.png)

If they can't download those certificates through the UI, how are they supposed to get access to the _default_ VCH configuration? 

>We don't generate client certificates/keys via the UI/API, so we don't allow them to be downloaded.

If those aren't generated at all, the Docker endpoint for the VCH created with the TLSverify selected (by default in the UI) will be completely inaccessible, which is actually a worse problem than I originally thought when I submitted this bug.

Notice this is also selected by default:
![screen shot 2017-12-13 at 3 20 43 pm](https://user-images.githubusercontent.com/3743903/33963051-3cd150dc-e019-11e7-9df5-286a87e596f2.png)

That emphasizes that it is TLSverify and not just TLS enabled by default. Further, if that is selected, the user is not forced to upload their own certificate, which seems to be the only way they would actually be able to use a VCH configured like this without generated user certificates to access the Docker endpoint.

**Comment by gigawhitlocks** [comment]
>This seems unrelated.

Also the reason that the Admiral issue is related is because either the vic-ui or Admiral, but preferably both, would warn the user that they have installed their VCH with `--tlsverify` enabled (since that is the default) and at the very least direct them to the documentation so that they can figure out where to go find their certificate to provide to Admiral when they go to add their VCH to their control panel.

Right now, if they use the defaults, they will wind up with a VCH that requires certificates to access that they do not know are necessary or where to retrieve them, and neither vic-ui nor Admiral will at any point warn them of this fact or give them any indication as to where to look in the documentation for the information they need.

**Comment by zjs** [comment]
> > The user only needs the server certificate if they chose to invoke the docker client with `--tlsverify` (vs. just `--tls`).
>
> This is false -- the user needs the certificates if `vic-machine` was called with `--tls-verify`.

I'm basing my statement on the [docker documentation](https://docs.docker.com/engine/security/https/#client-modes) which notes that providing the `tls`, `tlscert`, and `tlskey` arguments means: "Authenticate with client certificate, do not authenticate server based on given CA".

To me, this means that the user needs the client certificate and key, but not the server certificate, even if the VCH was created using `--tls-verify`, unless the docker client is invoked with `tlsverify`.

> If they can't download those certificates through the UI, how are they supposed to get access to the _default_ VCH configuration? ... if that is selected, the user is not forced to upload their own certificate, which seems to be the only way they would actually be able to use a VCH configured like this without generated user certificates to access the Docker endpoint.

Good catch. They aren't supposed to be able to advance without either uploading a client certificate or turning off client certificate verification. Filed #240 to track this.

> Also the reason that the Admiral issue is related is because either the vic-ui or Admiral, but preferably both, would warn the user that they have installed their VCH with --tlsverify enabled (since that is the default) and at the very least direct them to the documentation so that they can figure out where to go find their certificate to provide to Admiral when they go to add their VCH to their control panel.
> 
> Right now, if they use the defaults, they will wind up with a VCH that requires certificates to access that they do not know are necessary or where to retrieve them, and neither vic-ui nor Admiral will at any point warn them of this fact or give them any indication as to where to look in the documentation for the information they need.

Which certificate(s) does Admiral require?

**Comment by gigawhitlocks** [comment]
>Which certificate(s) does Admiral require?

If the user uses `--tlsverify` Admiral requires the user certificate in order to add the VCH under the `Add Container Host` screen. Admiral does not warn them of this, and doesn't produce an error that will indicate this is the issue if they try to use their username/password as credentials.

Further, the user may download the host certificates if they know that they need certificates but are not aware that those are the wrong certificates and try to add those as credentials in Admiral, which will also not work. 

I've got an email thread going with their team to try to illuminate the usability issues with their credentials management UI, but resolving #240 will resolve the most critical usability issue, because resolving #240 will prevent the user from creating a TLSverify-enabled VCH that is inaccessible, and it will also prevent them from creating a TLSverify-enabled VCH without being aware that they need certificates to access such a VCH.

**Comment by gigawhitlocks** [comment]
If the user disables TLSverify, Admiral does not require any credentials to add a VCH.

**Comment by jak-atx** [comment]
Closing as addressed with https://github.com/vmware/vic-ui/issues/240
