### ISSUE TITLE
VCH Creation Wizard does not prevent a user from advancing if they have not uploaded a client certificate

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#240]
**VIC version:**

OVA RC3

**Steps to reproduce:**

Navigate to the security page of the wizard. Leave client certificates enabled, but do not upload any.

![image](https://user-images.githubusercontent.com/408880/33963716-c803a452-e00a-11e7-83fe-d9d6cae5fe58.png)

**Actual behavior:**

The next button is enabled.

**Expected behavior:**

The next button should be disabled.

**Additional details as necessary:**

This is significant because it allows the user to create a VCH that they cannot connect to ― which is almost certainly not what they want or expect.

(Identified by @gigawhitlocks as a part of #237, but creating a separate issue to track this specific bug.)

**Comment by mdubya66** [comment]
@mlh78750 @mhagen-vmware please review. this doesn't seem like a ship stopper to me. Might be low hanging fruit though.

**Comment by mhagen-vmware** [comment]
Agreed not a ship stoppers, although high priority is appropriate

**Comment by cristianfalcone** [comment]
I'm adding the required Wizard validation for this, but please note that this is only for the UI side. API and CLI will continue to allow the same set of options without specifying client certs.
