### ISSUE TITLE
In Create VCH UI, DNS server is mandatory if you set static IP on public

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#249]
In the docs for the `vic-machine create --dns-server` option, we state the following:

---

A DNS server for the VCH endpoint VM to use on the public, client, and management networks. 

- If you specify a DNS server, vSphere Integrated Containers Engine uses the same DNS server setting for all three of the public, client, and management networks.
- If you do not specify a DNS server and you specify a static IP address for the VCH endpoint VM on all three of the client, public, and management networks, vSphere Integrated Containers Engine uses the Google public DNS service. 
- If you do not specify a DNS server and you use DHCP for all of the client, public, and management networks, vSphere Integrated Containers Engine uses the DNS servers that DHCP provides.

---

But, in the UI, it appears that a DNS server is mandatory if you set a static IP on public:

![dns_public](https://user-images.githubusercontent.com/16718369/34042369-a5cd34aa-e19c-11e7-8e8c-96b35fbd0dd1.jpg)

If you use DHCP on the public network but static IPs on client and management, then the DNS server is not required, and the NEXT button activates:

![dns-client-mgmt](https://user-images.githubusercontent.com/16718369/34042556-89d88c58-e19d-11e7-8273-039d82d2640a.jpg)

If you set a static IP on all 3 of public, client, and management, the DNS server is required. However, in the CLI if you set static IPs everywhere, then according to the doc the Google public DNS is used, if you don't set a DNS server:

![dns_all3](https://user-images.githubusercontent.com/16718369/34042622-dccadab0-e19d-11e7-92df-d7d059479cec.jpg)

So, it seems that the behaviour of the UI is inconsistent with the CLI, or at least with the behaviour of the CLI as documented until now.  So, is the doc statement above correct?

**Comment by cristianfalcone** [comment]
This screen is based on the following mockup:
https://vmware.invisionapp.com/share/N9C85VJ8M#/screens/239666107

I agree that this field should be optional based on the documentation, but the mockup is very specific on this. We need confirmation from @lweitzman or @zjs if DNS server field should be required or not.

@jak-atx

**Comment by zjs** [comment]
I agree that this is working as designed, but I don't recall why we didn't want to default to Google's DNS in the UI. Perhaps it's captured in the design process notes?

**Comment by jak-atx** [comment]
Closing as non-issue, working as designed.
