### ISSUE TITLE
Generated vic-machine create command has wrong argument for volume store

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#251]
**VIC version:**

1.3.0 OVA RC 4 (UI RC6)

**Steps to reproduce:**

Use the creation wizard to specify a VCH which has a default volume store (or, perhaps, any volume store).

**Actual behavior:**

The generated CLI command includes a `--volume-stores` option.

This will result in an error when executed: `Incorrect Usage: flag provided but not defined: -volume-stores`.

**Expected behavior:**

The generated CLI command should include a `--volume-store` option.

**Comment by AngieCris** [comment]
Generated CLI command still has the wrong volume store flag

**Comment by AngieCris** [comment]
@stuclem Can you please document that the generated CLI command has the wrong volume store flag? The workaround is to change `--volume-stores` to `--volume-store`. Thanks!

**Comment by jooskim** [comment]
@stuclem To give you more context on this, commit 10863aa was not cherry-picked onto our releases/1.3.0 branch and thus got omitted in v1.3.0 GA.

**Comment by stuclem** [comment]
Release note:

- <b>Generated `vic-machine` command includes incorrect `--volume-stores` option. [#251](https://github.com/vmware/vic-ui/issues/251)</b><br>In the Summary page of the Create VCH wizard, if you configured a volume store, the generated `vic-machine` command includes the option `--volume-stores`.  This is should be  `--volume-store`. Attempting to run the generated command results in the error `Incorrect Usage: flag provided but not defined: -volume-stores`.

   Workaround: Manually edit the generated command to correct the option name to `--volume-store`.

@jooskim is this OK?

**Comment by jooskim** [comment]
@stuclem Looks good! :shipit:

**Comment by zjs** [comment]
> This is should be

I think there's an extraneous "is" here.

**Comment by mdubya66** [comment]
Let's get this merged ASAP so it makes it into 1.3.1

**Comment by stuclem** [comment]
Fixed the extraneous "is" in the RN.

**Comment by andrewtchin** [comment]
just needs cherry pick pr

**Comment by jak-atx** [comment]
Merged to master. Cherry-pick PR https://github.com/vmware/vic-ui/pull/303
