### ISSUE TITLE
VCH Creation Wizard allows for selection of a host within a cluster

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#256]
**VIC version:**

1.3.0 OVA RC 4 (UI RC 6)

**Steps to reproduce:**

Launch the creation wizard, select a host in a cluster.

**Actual behavior:**

Creation fails with an error like `Failed to validate VCH: compute resource '/dc1/host/cluster1/...' not found`

**Expected behavior:**

Hosts within a cluster are visible, but not selectable as compute resources. (Stand-alone hosts, not in a cluster, should be both visible and selectable.)

**Additional information:**

This limitation may change in the future, but is captured in [the docs](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_placement.html#-compute-resource-):

> **NOTE:** You cannot deploy a VCH to a specific host in a cluster. You deploy the VCH to the cluster, and DRS manages the placement of the VCH on a host.

**Comment by AngieCris** [comment]
Screenshots:

The ESX hosts within the cluster are displayed in the list and are selectable:
![image2](https://user-images.githubusercontent.com/6562128/34076405-00d690fc-e2ac-11e7-9cca-1a15d128426b.png)

Selecting any one of the ESX hosts within the cluster as compute resource results in the creation error:
![screen shot 2017-12-15 at 4 25 49 pm](https://user-images.githubusercontent.com/6562128/34076410-22600294-e2ac-11e7-98cf-aca0654c7ab8.png)

**Comment by lgayatri** [comment]
Even I hit this issue. It is a generic workflow to choose ESX within a cluster as compute. Let us fix this for 1.4.

**Comment by mdubya66** [comment]
If we have a PR merged by Jan 17 then we can take this fix for 1.3.1
