### ISSUE TITLE
Expanding VCH fails with "Target validation failed: Datacenter "Datacenter" in --target is not found"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#257]
Build : vic-v1.3.0-rc4-2870-f8cc7317.ova

![image](https://user-images.githubusercontent.com/25006749/34067061-4ca38906-e241-11e7-8e03-f2cd55d29c54.png)

@jooskim @mdubya66

**Comment by lgayatri** [comment]
IMHO, do we need to show the deployment log here on this page?

**Comment by AngieCris** [comment]
@lgayatri Do you still have the values you put in the fields when creating this VCH? Or do you still have the generated CLI command for this deployment? I'll try to reproduce it
Pinging people for investigation: @zjs @jak-atx

**Comment by lgayatri** [comment]
@AngieCris , I tried again on my testbed and here is the generated CLI command for the VCH creation from ui wizard

```
./vic-machine-linux create --name LG-Test-17Dec --compute-resource /Datacenter/host/Cluster --image-store CPBU_2TB_01 --base-image-size 8GB --bridge-network vxw-dvs-3444-virtualwire-1-sid-5000-VCH-LS-1 --bridge-network-range 172.16.0.0/12 --public-network DPortGroup --tls-cname LG-Test-17Dec --organization LG-Test-17Dec --certificate-key-size 2048 --no-tlsverify --user Administrator@VSPHERE.LOCAL --thumbprint C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34 --target wdc-stvc3944-146-dhcp15.eng.vmware.com/Datacenter --ops-user lgayatri1@vsphere.local --ops-grant-perms
```

![image](https://user-images.githubusercontent.com/25006749/34077415-a27c023e-e329-11e7-9d17-397a1983f494.png)
@zjs @jak-atx

**Comment by jak-atx** [comment]
@cristianfalcone this looks like it will take some investigation as it's not clear what is happening from this error or how to reproduce it. Please reach out to @lgayatri if further info required for debugging.

@AngieCris @zjs let us know if you know what this error is, I've not seen it before.

**Comment by cristianfalcone** [comment]
"Datacenter" doesn't look like a valid datacenter MOID, which is required for log and create requests paths. Will try to reproduce this. Maybe we are not parsing the full VC object id to obtain the datacenter MOID in multi-datacenter systems.

**Comment by cristianfalcone** [comment]
@jak-atx @AngieCris @zjs 

I'v being able to reproduce this, adding a new datacenter in our dev environment. We are sending the same request in both single and multi datacenter configurations, with a success and an error response, respectively.

VC with two datacenters:

```
Request URL:https://10.25.200.100:8443/container/target/sc2-rdops-vm02-dhcp-93-240.eng.vmware.com/datacenter/datacenter-2/vch/vm-603/log?thumbprint=8A:FD:1E:AF:EC:D3:31:46:FB:E3:9E:89:86:4D:D1:20:03:95:A2:F4
Request Method:GET
Status Code:400 Bad Request
Remote Address:10.25.200.100:8443
Referrer Policy:no-referrer-when-downgrade

Target validation failed: Datacenter "Datacenter" in --target is not found
```

VC with a single datacenter:

```
Request URL:https://10.25.200.100:8443/container/target/sc2-rdops-vm02-dhcp-93-240.eng.vmware.com/datacenter/datacenter-2/vch/vm-603/log?thumbprint=8A:FD:1E:AF:EC:D3:31:46:FB:E3:9E:89:86:4D:D1:20:03:95:A2:F4
Request Method:GET
Status Code:200 OK
Remote Address:10.25.200.100:8443
Referrer Policy:no-referrer-when-downgrade

Dec 12 2017 00:56:17.551Z INFO  Starting API-based VCH Creation. Version: "v1.2.0-rc1 git:18841ed-dirty build:2017/11/23@16:22:42 id:15115 runtime:go1.8.3"
Dec 12 2017 00:56:17.551Z DEBUG Creating VMOMI session with thumbprint 8A:FD:1E:AF:EC:D3:31:46:FB:E3:9E:89:86:4D:D1:20:03:95:A2:F4
Dec 12 2017 00:56:17.568Z DEBUG Session Environment Info: 
Dec 12 2017 00:56:17.568Z DEBUG vSphere resource cache populating...
Dec 12 2017 00:56:17.573Z DEBUG Cached dc: 
Dec 12 2017 00:56:17.611Z DEBUG Cached folders: 
Dec 12 2017 00:56:17.611Z DEBUG Error count populating vSphere cache: (3)
Dec 12 2017 00:56:17.611Z DEBUG new validator Session.Populate: Failure finding cluster (): default compute resource resolves to multiple instances, please specify
Failure finding ds (): default datastore resolves to multiple instances, please specify
Failure finding pool (): default resource pool resolves to multiple instances, please specify
Dec 12 2017 00:56:17.611Z INFO  Validating target
Dec 12 2017 00:56:17.612Z DEBUG public network: IP {<nil> <nil>} gateway <nil> dest: []
Dec 12 2017 00:56:17.612Z DEBUG Unable to locate existing server certificate in cert path
Dec 12 2017 00:56:17.612Z INFO  Generating CA certificate/key pair - private key in virtual-container-host/ca-key.pem
Dec 12 2017 00:56:17.783Z INFO  Generating server certificate/key pair - private key in virtual-container-host/server-key.pem
Dec 12 2017 00:56:18.575Z INFO  Generating client certificate/key pair - private key in virtual-container-host/key.pem
Dec 12 2017 00:56:18.864Z DEBUG [69 114 114 111 114 32 111 112 101 110 105 110 103 32 105 110 112 117 116 32 102 105 108 101 32 118 105 114 116 117 97 108 45 99 111 110 116 97 105 110 101 114 45 104 111 115 116 47 99 101 114 116 46 112 101 109 10 118 105 114 116 117 97 108 45 99 111 110 116 97 105 110 101 114 45 104 111 115 116 47 99 101 114 116 46 112 101 109 58 32 78 111 32 115 117 99 104 32 102 105 108 101 32 111 114 32 100 105 114 101 99 116 111 114 121 10 117 110 97 98 108 101 32 116 111 32 119 114 105 116 101 32 39 114 97 110 100 111 109 32 115 116 97 116 101 39 10]
Dec 12 2017 00:56:18.864Z WARN  Failed to generate browser friendly PFX client certificate: exit status 1
Dec 12 2017 00:56:18.864Z INFO  Validating supplied configuration
Dec 12 2017 00:56:18.864Z DEBUG Setting scratch image size to 0 KB in VCHConfig
Dec 12 2017 00:56:18.941Z DEBUG No path element specified for image store - will use default
Dec 12 2017 00:56:18.963Z DEBUG Network configuration:
Dec 12 2017 00:56:18.963Z DEBUG 	Network: public NetworkEndpoint: &{{  public } false <nil> {<nil> <nil>}  [] false}
Dec 12 2017 00:56:18.963Z DEBUG 	Network: client NetworkEndpoint: &{{  client } false <nil> {<nil> <nil>}  [] false}
Dec 12 2017 00:56:18.963Z DEBUG 	Network: management NetworkEndpoint: &{{   } false <nil> {<nil> <nil>}  [] false}
Dec 12 2017 00:56:18.963Z DEBUG 	Network: bridge NetworkEndpoint: &{{ DistributedVirtualPortgroup:dvportgroup-15 bridge } true <nil> {<nil> <nil>}  [] false}
Dec 12 2017 00:56:18.968Z INFO  vDS configuration OK on "bridge"
Dec 12 2017 00:56:18.970Z INFO  vCenter settings check OK
Dec 12 2017 00:56:18.970Z DEBUG Checking firewall with management network IP {<nil> <nil>}
Dec 12 2017 00:56:18.995Z INFO  Firewall status: DISABLED on "/Datacenter/host/Cluster/10.192.111.11"
Dec 12 2017 00:56:19.005Z DEBUG filtered rules: [{{} nfsClient NFS Client false [{{} 0 65535 outbound dst tcp}]  true 0xc4201bd100}]
Dec 12 2017 00:56:19.005Z DEBUG filtered IPs: [10.162.202.170 10.166.2.117 10.162.202.236] networks: [] allIP: false rule: nfsClient
Dec 12 2017 00:56:19.005Z DEBUG fw unknown (dhcp) with fw disabled "/Datacenter/host/Cluster/10.192.111.11"
Dec 12 2017 00:56:19.005Z WARN  Firewall configuration on "/Datacenter/host/Cluster/10.192.111.11" may prevent connection on dst 2377/tcp outbound with allowed IPs: [10.162.202.170 10.166.2.117 10.162.202.236]
Dec 12 2017 00:56:19.006Z WARN  Unable to fully verify firewall configuration due to DHCP use on management network
Dec 12 2017 00:56:19.006Z WARN  VCH management interface IP assigned by DHCP must be permitted by allowed IP settings
Dec 12 2017 00:56:19.006Z WARN  Firewall configuration may be incorrect if firewall is reenabled on hosts:
Dec 12 2017 00:56:19.006Z WARN  	"/Datacenter/host/Cluster/10.192.111.11"
Dec 12 2017 00:56:19.006Z INFO  Firewall must permit dst 2377/tcp outbound to the VCH management interface if firewall is reenabled
Dec 12 2017 00:56:19.008Z INFO  vCenter settings check OK
Dec 12 2017 00:56:19.212Z INFO  License check OK on hosts:
Dec 12 2017 00:56:19.212Z INFO    "/Datacenter/host/Cluster/10.192.111.11"
Dec 12 2017 00:56:19.215Z INFO  DRS check OK on:
Dec 12 2017 00:56:19.215Z INFO    "/Datacenter/host/Cluster"
Dec 12 2017 00:56:19.237Z DEBUG Datacenter: "Datacenter", Cluster: "ClusterComputeResource:domain-c7", Resource Pool: "/Datacenter/host/Cluster/Resources"
Dec 12 2017 00:56:19.260Z INFO  Creating Resource Pool "virtual-container-host"
Dec 12 2017 00:56:19.277Z INFO  Creating appliance on target
Dec 12 2017 00:56:19.277Z DEBUG generating new config secret key
Dec 12 2017 00:56:19.287Z DEBUG Setting "public" to slot 1184
Dec 12 2017 00:56:19.287Z INFO  Network role "client" is sharing NIC with "public"
Dec 12 2017 00:56:19.287Z INFO  Network role "management" is sharing NIC with "public"
Dec 12 2017 00:56:19.293Z DEBUG Setting "bridge" to slot 1216
Dec 12 2017 00:56:20.161Z DEBUG properties: [config.files.vmPathName summary.runtime.connectionState]
Dec 12 2017 00:56:20.163Z DEBUG vm folder name: "virtual-container-host"
Dec 12 2017 00:56:20.163Z DEBUG vm inventory path: "/Datacenter/vm/virtual-container-host"
Dec 12 2017 00:56:20.367Z DEBUG properties: [config.files.vmPathName summary.runtime.connectionState]
Dec 12 2017 00:56:20.369Z DEBUG generating new config secret key
Dec 12 2017 00:56:21.628Z INFO  Uploading images for container
Dec 12 2017 00:56:21.629Z INFO  	"bootstrap.iso"
Dec 12 2017 00:56:21.630Z INFO  	"appliance.iso"
```

**Comment by jak-atx** [comment]
It looks like we are passing the correct datacenter MOID in the url as 'datacenter-2' which i see here in the managed objects: https://10.192.93.240/mob/?moid=datacenter-2

The name of it is 'Datacenter' however, but we aren't passing that afaik.

**Comment by AngieCris** [comment]
Some API related investigation:

This is where the datacenter path is set for the validator:

https://github.com/vmware/vic/blob/master/lib/apiservers/service/restapi/handlers/common.go#L99

The wizard says `Target validation failed: Datacenter "Datacenter" in --target is not found`. This comes from here:

https://github.com/vmware/vic/blob/master/lib/install/validate/validator.go#L212


So here's what happened:
in the API we set the session datacenter fields:
```
		v.DatacenterPath = dc.Name()
		v.Session.DatastorePath = v.DatacenterPath
		v.Session.Finder.SetDatacenter(dc)
```
And in validator we're checking:
```
	if v.allowEmptyDC && v.DatacenterPath == "" {
		return nil
	}
	if v.Session.Datacenter != nil {
		v.DatacenterPath = v.Session.Datacenter.InventoryPath
		return nil
	}
	var detail string
	if v.DatacenterPath != "" {
		detail = fmt.Sprintf("Datacenter %q in --target is not found", path.Base(v.DatacenterPath))
	} else {
		// this means multiple datacenter exists, but user did not specify it in --target
		detail = "Datacenter must be specified in --target (e.g. https://addr/datacenter)"
	}
```
Apparently to reach the `fmt.Sprintf("Datacenter %q in --target is not found", path.Base(v.DatacenterPath))` line, `v.Session.Datacenter` is nil but `v.DatacenterPath` is not nil.
We set the `v.DatacenterPath` in the API but what about `v.Session.Datacenter`
The `v.Session.Finder.SetDatacenter(dc)` just sets the dc in finder I guess

Just some input for relevant people @zjs

**Comment by AngieCris** [comment]
The root cause could very possibly be that the datacenter object in validator session config is not set. We did set the datacenter path, but never the datacenter object
If the datacenter in validator session is never set, the correspondent validation step should technically always fail. @lgayatri @cristianfalcone is it 100% reproduceable for you guys?

PR: https://github.com/vmware/vic/pull/6994

**Comment by lgayatri** [comment]
@AngieCris , yes 

This is my current UI screenshot

![image](https://user-images.githubusercontent.com/25006749/34242859-df84f5e2-e643-11e7-8c31-bcf3c8b4859f.png)

**Comment by AngieCris** [comment]
@lgayatri Does the same failure happen every time you create a new VCH as well?

**Comment by AngieCris** [comment]
The error message is `Target validation failed: Datacenter "Datacenter" in --target is not found`. This message comes from validator. This `"Datacenter"` is the dc path that validator gets. It's complaining that validator can't find the dc by the path.
The dc path should be the dc management object inventory path. If I remember it correctly, it should be sth like `datacenter-2`? @jak-atx If so, then the dc path is not correctly set.

Snippet from the API code that sets the dc path:
```
		v.DatacenterPath = dc.Name()
		v.Session.DatastorePath = v.DatacenterPath
		v.Session.Finder.SetDatacenter(dc)
```
We did in `v.DatacenterPath = dc.Name()` to set dc path to dc object inventory path. But in the second line there's a typo, it should be `v.Session.DatacenterPath = v.DatacenterPath`. So the validator session dc path is not correctly set. The `"Datacenter"` in the error message looks like a default.
If the above analysis is correct, this pr should fix the issue: https://github.com/vmware/vic/pull/6994

@lgayatri Do you also see this error every time when you use the wizard to create a VCH?

**Comment by lgayatri** [comment]
@AngieCris , so far I was not able to create VCH from UI due to issues and latest one being https://github.com/vmware/vic-ui/issues/208.

I created VCH using vic-machine* CLI

**Comment by AngieCris** [comment]
@lgayatri I believe the error you updated in #208 has the same root cause as this one

**Comment by AngieCris** [comment]
@lgayatri I believe this error have the same root cause as the error you updated in #208

**Comment by lgayatri** [comment]
@AngieCris Ok

**Comment by lgayatri** [comment]
Verified on RC5,this issue is fixed

![image](https://user-images.githubusercontent.com/25006749/34513723-b4287a44-f08f-11e7-9ff0-4708886db6e5.png)
