### ISSUE TITLE
Create VCH wizard allows auto-generation of client certs that you cannot obtain, meaning that resulting VCH is inaccessible

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#261]
According to @zjs via Slack when I asked about how to obtain auto-generated client certs for VCHs created in the UI, "The wizard only supports auto-generation of a server certificate."

However, if you leave all of the default options in the Security page, without disabling client verification or uploading a CA for client certs, you are allowed to click **Next**:

![tls1](https://user-images.githubusercontent.com/16718369/34163619-83ea759e-e4d7-11e7-9db0-52d494783616.jpg)

Looking at the generated `vic-machine` command, the options used will generate a VCH that uses auto-generated server, client and CA certs:

![tls2](https://user-images.githubusercontent.com/16718369/34163735-d955a8fa-e4d7-11e7-8417-05e9f6249661.jpg)

This is confirmed in the output:

![tls3](https://user-images.githubusercontent.com/16718369/34163752-e6f075ee-e4d7-11e7-91df-f4c7072e4f17.jpg)

However, you cannot access the generated client certs, which according to @zjs are stored in vSphere metadata on the Endpoint VM. Without the client certs, you cannot register the VCH with Management Portal or connect a Docker client to it. 

So, unless I'm missing something major, if you click through the default settings in the Security page, the Create VCH wizard gives you a VCH that you cannot access.

**Comment by stuclem** [comment]
I suppose that if @zjs was correct when he said that auto-generated client certs are not supported, then you must either disable client verification, or upload a custom CA file. You should not be able to click **Next** if client verification is on and you haven't uploaded a CA.

**Comment by jak-atx** [comment]
"..if you leave all of the default options in the Security page, without disabling client verification or uploading a CA for client certs, you are allowed to click Next"

This has been fixed in https://github.com/vmware/vic-ui/issues/240

**Comment by stuclem** [comment]
Thanks @jak-atx. I'm using the most recent build of the OVA and that fix isn't in there yet. Admittedly that build was from last Friday.

**Comment by stuclem** [comment]
As a recap for my own education/sanity, can someone please confirm that the following table includes all possibilities for certificate use in both the UI and CLI:

|**Type of cert**|**Available in**|
|---|---|
|Auto-generated server cert + custom CA (and therefore custom client certs)|CLI and UI| 
|Auto-generated server cert + no client verification|CLI and UI| 
|Auto-generated server cert + auto-generated client cert + auto-generated CA|CLI only|
|Custom server cert + custom CA (and therefore custom client certs)|CLI and UI|
|Custom server cert + auto-generated client cert + auto-generated CA|CLI only|
|Custom server cert + no client verification|CLI and UI|
|No server or client certs|CLI and UI|

@pdaigle @zjs @hickeng @jak-atx am I missing a supported combo? Thanks in advance!

**Comment by stuclem** [comment]
Actually, @AngieCris, if this is already fixed in 1.3, this is more of a doc issue. Moving to `vic-product`.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic-product #1276](https://github.com/vmware/vic-product/issues/1276) via [**ZenHub**](https://www.zenhub.com/)
