### ISSUE TITLE
Critical : VIC UI shows incorrect inventory tree

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#270]
@mdubya66 @jooskim @AngieCris 

Build - RC5 - https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova

![image](https://user-images.githubusercontent.com/25006749/34480399-34eabffc-efd2-11e7-904f-feabcd248be1.png)

Hosts are actually in Datacenter/Cluster

![image](https://user-images.githubusercontent.com/25006749/34480433-6c5f9962-efd2-11e7-8d99-e91e9f7b890f.png)

This is a critical issue and is must fix for 1.3

**Comment by jooskim** [comment]
This issue is also fixed in the mentioned PR. Closing the issue
