### ISSUE TITLE
Compute resource selector widget hangs in a certain VC configuration

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#274]
**VIC UI version:**
v1.3.0 / 505+

**Steps to reproduce:**
1. Configure the VC to have one datacenter, one standalone host and two empty clusters
![image](https://user-images.githubusercontent.com/3834071/34496404-0f2fb104-efbf-11e7-9ed1-fdb98bf5d8fd.png)

2. Deploy the VIC product OVA to the standalone host (which needs to have at least 8GB of ram and 150GB of disk space)
3. Install the UI plugin
4. Log into the H5 Client and navigate to the Virtual Containers Hosts view then open the VCH creation wizard
5. Proceed through the steps to create a VCH

**Actual behavior:**
User should be able to choose the standalone host as compute resource for a new VCH

**Expected behavior:**
Compute resource selector widget hangs

![image](https://user-images.githubusercontent.com/3834071/34496479-60b3af58-efbf-11e7-86bb-653358ae5423.png)

**Additional details as necessary:**
After an investigation I figured that this issue is seen when there is more than one empty cluster found in the VC inventory and is caused by an improper array mutation in the UI code.

**Comment by jooskim** [comment]
@stuclem Hi Stuart, this issue impacts 1.3.0 GA and needs to be documented. A way to reproduce the issue is to have at least two empty Clusters in the VC inventory so a workaround would be to delete those empty Clusters.

**Comment by stuclem** [comment]
Release note:

- <b>Compute resource selector does not work with two empty clusters in inventory. [#274](https://github.com/vmware/vic-ui/issues/274)</b><br>In the Compute Capacity page of the Create VCH wizard, if your vCenter Server inventory includes at least two empty clusters, the compute resource selector does not populate and you cannot continue with the deployment of the VCH.

   Workaround: Delete the empty clusters from the vCenter Server inventory.

@jooskim is this OK?

**Comment by jooskim** [comment]
@stuclem 🚢 🇮🇹

**Comment by AngieCris** [comment]
@jooskim Can you confirm that it only happens when there're at least two empty clusters? Will it hang when there's one empty cluster and a standalone host?

**Comment by jooskim** [comment]
@AngieCris @stuclem It will not hang in that case. It only happens when there are at least two empty clusters. I confirmed this issue was caused by an incorrect array manipulation.

**Comment by jooskim** [comment]
Adding for 1.3.1 proposal

**Comment by stuclem** [comment]
Thanks @jooskim and @AngieCris. Removing kind/note as the RN entry is approved.

**Comment by Chesky7** [comment]
Had the same issue, works!
