### ISSUE TITLE
Networks panel hangs in our dev VC

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#275]
<img width="1416" alt="screen shot 2018-01-02 at 1 31 41 pm" src="https://user-images.githubusercontent.com/15793168/34497027-5cd64f92-efc1-11e7-8e52-b23796ab0085.png">

No errors are shown but the spinner doesn't stop. Networks array seems to come back empty.

VC: 10.160.123.166

Needs further investigation.

**Comment by jooskim** [comment]
The VC above is our dev environment and currently does not have any distributed switch set up, which is what's causing the Networks step to crash. Currently the Networks step fetches only port groups under all available distributed switches but not default networks such as VM Network. A viable fix for this issue would be to update the Angular service to get default networks from the VC inventory.

**Comment by AngieCris** [comment]
Should we add a release note on it? Maybe sth along the lines of "If you don't have distributed switch set up, the create wizard will hang"

**Comment by jooskim** [comment]
Good idea @AngieCris . @stuclem what do you think?

**Comment by jooskim** [comment]
A viable fix would be to show a warning to the user that a distributed virtual switch must be created in order to proceed.

**Comment by stuclem** [comment]
Added release note:

- <b>Configure Networks page does not load if no distributed port groups exist. [#275](https://github.com/vmware/vic-ui/issues/275)</b><br>In the Configure Networks page of the Create VCH wizard, if your vCenter Server setup does not include any distributed port groups, the page does not populate and you cannot continue with the deployment of the VCH.

   Workaround: Create at least two distributed port groups, for the bridge and public networks.

@AngieCris and @jooskim is this OK? Thanks!

**Comment by AngieCris** [comment]
@stuclem Looks good!

**Comment by jooskim** [comment]
@stuclem LGTM
