### ISSUE TITLE
Testing: VCH create wizard static IP

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#283]
**Details:**
We need a test for VCH create wizard that uses a static IP in the networks config

**Acceptance Criteria:**
Be able to display a test that covers inputing static IP for VCH create from wizard

**Comment by andrewtchin** [comment]
document procedures
try to do this automatically on nimbus

**Comment by AngieCris** [comment]
Static IP service on nimbus guide, might be relevant: https://confluence.eng.vmware.com/display/DevToolsDocKB/15.6+Static+IP+Service

**Comment by jooskim** [comment]
After giving this story a little thought I came to think that verifying the actual functionality of a VCH created with a static IP might be out of scope for UI testing. The test cases should be covering:

1.  Provide a correct static IP in CIDR format and gateway and verify successful creation
2. Provide an IP in an incorrect format and verify the validation error shows up correctly

Above cases can be covered in individual unit tests. So it should be taking less time than what was originally expected. Adjusting the estimate to 2

**Comment by jooskim** [comment]
Turns out the cases are already covered here:
https://github.com/vmware/vic-ui/blob/master/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/networks/networks.component.spec.ts#L132

Closing as already done.
