### ISSUE TITLE
H5 Client HSUIA tests fail on IE11

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#290]
VIC UI plugin test cases should run in the same way regardless of which platform and browser they run on. However, the tests would fail on IE11 in our Windows environment because of some differences. Some of the findings are as follows:

Details to be added

**Comment by jak-atx** [comment]
Closing as obsolete now that we are moving away from HSUIA testing. Will need to verify this scenario in this issue https://github.com/vmware/vic-ui/issues/298
