### ISSUE TITLE
VCH wizard no-tls-verify workflow

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#296]
**Details:**
The workflow needs to be re-examined as it seems a bit confusing around the secure settings. 

Both the "Enable secure access to this VCH" and "Clients will need to authenticate" do the same thing (turn off no-tls-verify).

<img width="1575" alt="screen shot 2018-01-05 at 2 55 55 pm" src="https://user-images.githubusercontent.com/15793168/34628079-b66cfc36-f228-11e7-8749-02427690da17.png">

Also @pdaigle mentioned that there should be a way to disable secure access but still have access to update the "Registry Access"

<img width="863" alt="screen shot 2018-01-05 at 2 58 57 pm" src="https://user-images.githubusercontent.com/15793168/34628181-15a6d60e-f229-11e7-82d0-696ab68e6a2e.png">

Need to work with UX on this to refine this workflow.
cc: @lweitzman

**Comment by zjs** [comment]
Related: #161

**Comment by lweitzman** [comment]
updated the mockups to include a new 4 page sequence. it adds a new TOC item for registry access and simplifies the security page by removing the tabs. you can access it thru the table of contents or directly here...

https://vmware.invisionapp.com/share/CBFATDIEU#/273066358_VCH_Wizard-Security-00_Copy
