### ISSUE TITLE
VCH Wizard resource selection 

### ISSUE THREAD

**Issue by emeirell** [vmware/vic-ui#307]
**VIC version:**
VIC 1.3.0

**Deployment details:**
On my vCenter environment, I have 2 clusters, one Management and a Resource one, each cluster has it's own vDS and datastores.
VCH will be provisioned on the Resource cluster only.

**Steps to reproduce:**
When creating the VCH through the Wizard, it just shows the PortGroups from the vDS of the Management Cluster.

<img width="1023" alt="compute" src="https://user-images.githubusercontent.com/22505995/35051634-d97e2782-fb8c-11e7-99ac-9daa6fe034ba.png">

<img width="1025" alt="networks" src="https://user-images.githubusercontent.com/22505995/35051667-eb12151c-fb8c-11e7-8cca-75eb4b4f17fb.png">

<img width="352" alt="captura de tela 2018-01-17 as 13 45 38" src="https://user-images.githubusercontent.com/22505995/35051679-f20a00b4-fb8c-11e7-994f-247bd0a4a7ec.png">

**Expected behavior:**
The PortGroups and the Datastores should be the ones available based on the Compute Resource selected on the Compute Capacity section only, everything else, should be filter out.

**Comment by emeirell** [comment]
I notice something else, apparently when you first select the Compute Resource,  the portgroups are listed properly, but if you go back and change the Compute Resource, the list of portgroups are not being refreshed

**Comment by jooskim** [comment]
This issue was caused by incorrect caching of port groups. I just submitted a PR to fix it and properly list all port groups that the selected compute resource has access to.

**Comment by jhedman2** [comment]
Quick update, just upgraded everything to current stage build of 1.3.1 (vic-stage-3191-v1.3.1-dev-3191-06ca9cf3.ova).  First run through wizard worked great, displayed all port groups as expected, but after deleting the VCH and attempted a new deployment, only two of the distributed port groups are showing up.  Any ideas?  Or did I just jump the gun with 1.3.1?  Do I need to be waiting for 1.4.0?
