### ISSUE TITLE
Download VCH Certificate error

### ISSUE THREAD

**Issue by emeirell** [vmware/vic-ui#311]
**VIC version:**
VIC 1.3.0

**Deployment details:**

HTML5 VIC plugin shows an option to download VCH certificate for hosts which were created without a certificate at all, option --no-tls.
So if the user mistakenly  click on download certificate it generates an error "Error downloading VCH certificate"
It might confuse the users.

<img width="1422" alt="cert_error" src="https://user-images.githubusercontent.com/22505995/35101395-8b6dda82-fc46-11e7-8437-70eccde2f74a.png">

**Steps to reproduce:**
- create a VCH with --no-tls option
- go to VIC plugin and select download VCH certificate

**Expected behavior:**
If VCH does not have a certificate the option to Download VCH certificate should not be presented or grayed out.

**Comment by mdubya66** [comment]
PM would like to see this in 1.3.1. We need to get it merged today and cherry picked for inclusion in RC1 on 1/19

**Comment by jak-atx** [comment]
This one we have no way to fix at the moment. It would take the API letting us know if the cert is available. 
@AngieCris @zjs is this something we can determine?

**Comment by zjs** [comment]
You can determine whether TLS is enabled using the inspect API (`GET` on the VCH resource).

**Comment by AngieCris** [comment]
@jak-atx 
The work API could do is to return meaningful error message for request to certificate endpoint of VCH created by `--no-tls`. That happens after the user clicks on the `Download Certificate` button.
But we might want to gray out the `Download Certificate` option for VCHs created with `--no-tls`. UI side might have to use API inspect to determine that forehand.

**Comment by AngieCris** [comment]
For VCH created with `--no-tls` option, from the network inspect tab it seems like the API returns meaningful error message. The response json:
`{"message":"No certificate found for VCH vm-120"}`
On the wizard, a generic error message is shown:
`Error downloading VCH certificate!` 
It looks like a default for all errors from certificate endpoint. We might want to grab the API response and display the API error message on the UI side.

**Comment by jak-atx** [comment]
Displaying the correct error message for now. Will address disabling the function in subsequent release.

**Comment by AngieCris** [comment]
@jak-atx If we still have a plan of graying out the `Download Certificate` button for no-tls VCHs, can you file another issue tracking it?
Also do we have an issue in the ui repo tracking the issue of using API list to show the VCH inventory list?

**Comment by jak-atx** [comment]
@AngieCris I will file those issues today. Thanks.

**Comment by jak-atx** [comment]
Issues #322 and #323 have been submitted to track these.

**Comment by AngieCris** [comment]
Thanks! @jak-atx
