### ISSUE TITLE
Issue #307 connection - continued in 1.3.1 Dev release.

### ISSUE THREAD

**Issue by jhedman2** [vmware/vic-ui#329]
Originally posted to issue #7127 which was linked to #307.

Quick update, just upgraded everything to current stage build of 1.3.1 (vic-stage-3191-v1.3.1-dev-3191-06ca9cf3.ova). First run through wizard worked great, displayed all port groups as expected, but after deleting the VCH and attempted a new deployment, only two of the distributed port groups are showing up. Any ideas? Or did I just jump the gun with 1.3.1? Do I need to be waiting for 1.4.0?

**Comment by jooskim** [comment]
If you could provide, screen recording would be very helpful for me in figuring out if this is a new issue.

**Comment by jhedman2** [comment]
Ugh, so of course, as I went back to take screen shots it's working again.  I'll keep an eye on it but the behavior was this, I deployed a VCH and everything was fine, deleted it to change some settings, but when I went to recreate it, the DPG's were showing all of them, only essentially one of them.

I'll try it a few more times to see if i can break it again.  Sorry.

**Comment by jooskim** [comment]
Marking it as no repro until we get more details

**Comment by jak-atx** [comment]
Closing as non reproducible.
