### ISSUE TITLE
Create VCH wizard says custom server key should be encrypted

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#338]
**VIC-UI version:**

v1.3.1-rc1.663

**Actual behavior:**

On the Security page, if you select Existing to upload a custom server certificate, the onscreen text for the private key says "Select an **encrypted** key pem file":

![serverkey-encrypted](https://user-images.githubusercontent.com/16718369/35682666-c453d4f2-0761-11e8-9b97-8095b10f2ca9.jpg)

**Expected behavior:**

My understanding is that the key file must **not** be encrypted. This is what we have always documented, up to and including 1.3.0: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_cert_options.html#server-key

bug2185779

**Comment by AngieCris** [comment]
Cc: @zjs @jak-atx @jooskim According to the doc, server private key must not be encrypted. I'm not very familiar with the certificate side of things, do we have a reason why we want the user to upload encrypted server private key here?

**Comment by zjs** [comment]
I don't think uploading an encrypted key would work; we don't allow the user to supply a passphrase. It's likely just a textual error.

**Comment by zjs** [comment]
Despite being a customer-reported issue, this does not seem significant enough to mention in the release notes.
