### ISSUE TITLE
H5C UI : Pagination for viewing Containers

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#339]
Looks like VIC 1.3.1 RC2 missed picking https://github.com/vmware/vic-ui/pull/229 
Build : https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.1-rc2-3344-132fb13d.ova

Cant see pagination containers view. This issue was earlier reported and fixed in https://github.com/vmware/vic-ui/issues/215 

![image](https://user-images.githubusercontent.com/25006749/35730415-127e1990-0838-11e8-8a3a-e21ff91a0b42.png)

@mdubya66 @jak-atx @mhagen-vmware

**Comment by jooskim** [comment]
It turns out that this issue was not addressed properly in #216 . I can see the same issue even in my latest dev build. Closing this issue and reopening #215

**Comment by lgayatri** [comment]
Verified on RC3 https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.1-rc3-3401-132fb13d.ova. Issue has been fixed.
