### ISSUE TITLE
UI Integration tests (vch create)

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#34]
@jak-atx commented on [Thu Oct 19 2017](https://github.com/vmware/vic/issues/6597)

**Details:**
Follow up to https://github.com/vmware/vic/issues/6453 . When the endpoint is ready we need to finish up the current integration test cases to include the request/response from the API and landing page. 

**Acceptance Criteria:**
Verify that the integration tests for VCH create wizard UI are complete end to end from pulling up the wizard to getting a valid of response from vic-machine-service.

**Comment by jooskim** [comment]
Nightly tests are now back online with some cases skipped for Selenium & browser issues. However, these cases have been manually tested and they work as expected. Making those cases work is a future work considering we have a lot currently in our queue.
