### ISSUE TITLE
Upon upgrade from 1.3.0 to 1.3.1 RC2, vic_v1.3.1 tar still refers to RC1

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#340]
1. Upgraded to https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.1-rc2-3344-132fb13d.ova form VIC 1.3.0
2. Browsed to view files
![image](https://user-images.githubusercontent.com/25006749/35730774-5c0dbc54-0839-11e8-99f5-70b01af83c4b.png)
3. Was expecting the version to show as rc2 instead of rc1.
@andrewtchin @mdubya66 

```
Set new data version: appliance=v1.3.1-rc2-3344-132fb13d
harbor=harbor-offline-installer-v1.3.0.tgz
engine=vic_v1.3.1-rc1.tar.gz
admiral=vmware/admiral:vic_v1.3.0 6f1d13decebe
```

**Comment by mdubya66** [comment]
This is expected. THere were no changes to engine. We can have mixed versions. For example in 1.3.1 Harbor and Admiral will remain at 1.3.0.

**Comment by lgayatri** [comment]
Thanks @mdubya66
