### ISSUE TITLE
Port groups under a network folder don't show up in the wizard

### ISSUE THREAD

**Issue by jooskim** [vmware/vic-ui#389]
**do not merge until after 1.4 release is tagged**

**VIC-UI version:**
1.3

**Additional details:**
Customers reported that in the Create VCH wizard they don't see port groups for switches they have in the VC inventory. Port groups that did not show up were under a network folder.

![image](https://user-images.githubusercontent.com/3834071/37472684-adc0f0f4-283a-11e8-8d17-4c025f2a5f9d.png)

**Steps to reproduce:**
1. Create a network folder in VC and create at least one distributed virtual switch, and add at least a host to it
2. Create two port groups for the switch
3. In the wizard try to create a VCH using the two port groups for bridge and client network respectively

**Actual behavior:**
Port groups do not show up

**Expected behavior:**
User should be able to see and select the port groups

**Comment by jooskim** [comment]
Initial findings:
1. All of our use cases so far have been under an assumption that DV switches are always on the root level, but once you nest them under a network folder, they do not get picked up by the UI
2. According to `getDistributedPortGroups()` in `create-vch-wizard.service.ts` we perform the following operations to get the list of port groups of the given DC object:
  - get networking tree for a given DC object
  - filter them such we get only entires of type `DcDvs`
  - make API calls to get DV portgroup entries and their host entries information
3. The problem with this current code is that it assumes that there would be only nodes whose nodeTypeId is `DcDvs` that the user can choose from, when the user should also be able to choose from a folder. In this case, a folder has nodeTypeId `DcNetworkFolder` and `/ui/tree/children` call should be made recursively to fetch the leaf nodes which have type `DcDvs`.

**Comment by mlh78750** [comment]
Another customer experienced this issue as reported on internal slack.

**Comment by andrewtchin** [comment]
Add a test as part of this story
