### ISSUE TITLE
Update VCH Management UI to support VM-Host Affinity

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#401]
As a part the VCH Creation Wizard, users should be able to select a DRS VM Group to be supplied to the API.

**Comment by jak-atx** [comment]
Need UX for this.

**Comment by jak-atx** [comment]
cc @lweitzman

**Comment by lweitzman** [comment]
Added vm-host affinity to the mockups (thanks @zjs ). https://vmware.invisionapp.com/share/THCZQ0HN2#/239666099_Create_VCH_Wizard_-_2_Compute_-_Advanced

**Comment by javierfz1980** [comment]
@lmalvins I've created a new issue in order to track this e2e integration: https://github.com/vmware/vic-ui/issues/460

**Comment by zjs** [comment]
I think this is worth release noting, probably as an enhancement.

**Comment by stuclem** [comment]
Documented as a new feature in https://github.com/vmware/vic-ui/releases/tag/v1.4.3 and documented fully in https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vch_compute.html#hostaffinity. Removing doc labels.
