### ISSUE TITLE
6.7 VCSA's H5C shows "Could not find any VIC appliance VM" despite successful registration

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-ui#429]
#For stories, please include the information below:

**User Statement:**

6.7 VCSA's H5C shows "Could not find any VIC appliance VM" despite successful registration

**Details:**
![image](https://user-images.githubusercontent.com/25006749/38671026-f3aef8a2-3e67-11e8-9758-18fe29ff1b2b.png)

![image](https://user-images.githubusercontent.com/25006749/38671051-01096f28-3e68-11e8-9513-8ad82078596c.png)

![image](https://user-images.githubusercontent.com/25006749/38671081-0ce2d94c-3e68-11e8-8ebb-136da5ceaf7b.png)

**Acceptance Criteria:**

User should not see any error message on the UI screen.

**VIC-UI version:** v1.3.1-rc2.1085

[In the VIC plugin] > Summary tab > Version

**Platform details:**

Which platform are you using? (Windows, Mac OS, Linux, etc) : WIndows

**Browser details:**

Which browser are you using? (IE, Chrome, Firefox, etc) : Chrome

**Additional details:**

If applicable please include the following:

Error messages. (In the UI or from the browser's developer tools)

Request/response, including headers (from the browser's developer tools).

**Steps to reproduce:**
1. Installed a 6.7 embedded VCSA , deployed 1.4 OVA vic-dev-v1.4.0-dev-4398-3c5cd51a.ova
2. Registered the OVA with VCSA and Installed the UI plugin, restarted the virgo services
3. Upon accessing the Home-> Shortcuts-> vSphere Integrated containers -  observed the reported issue.

**Expected behavior:**
User should not see any error on this screen.

**Logs:**

https://w2hs2-testvm08.eng.vmware.com/ui/vic/rest/services/get-vic-appliances
```
{"stackTrace":"java.lang.NullPointerException\n\tat com.vmware.vic.model.VicApplianceVm.<init>(VicApplianceVm.java:60)\n\tat com.vmware.vic.PropFetcher.getVicApplianceVms(PropFetcher.java:441)\n\tat com.vmware.vic.services.VicApplianceServiceImpl.getVicAppliancesList(VicApplianceServiceImpl.java:39)\n\tat sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)\n\tat org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)\n\tat org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)\n\tat org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)\n\tat org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\n\tat org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)\n\tat com.sun.proxy.$Proxy769.getVicAppliancesList(Unknown Source)\n\tat com.vmware.vic.mvc.ServicesController.getVicAppliances(ServicesController.java:129)\n\tat sun.reflect.GeneratedMethodAccessor654.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:622)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:729)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com.vmware.vise.security.SessionManagementFilter.doFilter(SessionManagementFilter.java:165)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)\n\tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)\n\tat org.eclipse.virgo.web.tomcat.support.ApplicationNameTrackingValve.invoke(ApplicationNameTrackingValve.java:33)\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:748)\n","message":null}
```

**Comment by lgayatri** [comment]
@mdubya66 @mhagen-vmware

**Comment by javierfz1980** [comment]
I’ve created a fresh environment:
https://10.161.177.181

I’ve deployed:
vc 6.7 - Version 6.7.0.1150 Build 8033102
ova - vic-dev-v1.4.0-dev-4398-3c5cd51a.ova
vic-ui - v1.3.1-rc2.1085

There are no signs of the error... I'll keep looking.

In the mean time, I’ve seen this error a couple of times before on different environments, and it was always related with some mistake during vic installation… could you please try again with a new fresh environment from the scratch ?

Thanks

**Comment by mdubya66** [comment]
Javier, Her environment is our official scale testbed. Please work directly with @lgayatri to diagnose what she is seeing.

**Comment by javierfz1980** [comment]
Issue seems to be fixed after vic ova and ui redeploy/reinstall.

[https://w2hs2-testvm08.eng.vmware.com](url)
vic-ui - v1.3.1-rc2.1085
ova - vic-dev-v1.4.0-dev-4398-3c5cd51a

Please take a look and confirm,

Thanks.

<img width="1421" alt="containers" src="https://user-images.githubusercontent.com/36636787/38759384-0d91f56e-3f4c-11e8-97f4-f997741386fb.png">
<img width="1421" alt="summary" src="https://user-images.githubusercontent.com/36636787/38759385-0db57b2e-3f4c-11e8-8444-ffa049c1991e.png">
<img width="1421" alt="vch" src="https://user-images.githubusercontent.com/36636787/38759386-0dd7cbfc-3f4c-11e8-9e0d-2dd571ffe99d.png">

**Comment by javierfz1980** [comment]
Error could be the network selected during OVA deployment wizard. It was selected VM-network, but it should be VM-traffic since theres no dhcp on VM Network. VM has to be connected to VM-Traffic.

**Comment by lgayatri** [comment]
Since we are providing static IP address, is it necessary for the DHCP to be running on the first network?

**Comment by javierfz1980** [comment]
AFAIK if you want to provide static IP you don't need DHCP... not sure how that will impact during the ova deployment/installation.

@andrewtchin could you please help us with @lgayatri question ?

**Comment by andrewtchin** [comment]
When was the static IP address provided? When I looked at this environment last week the appliance did not have a good IP address. The network that the appliance is connected to must have a route to the vCenter server and when I looked at this it did not have one. If the vCenter server can't reach the IP of the appliance, it doesn't matter if it's a static or dynamic IP.

**Comment by jak-atx** [comment]
@lgayatri can you update if you are still having any issue with this?

**Comment by jak-atx** [comment]
Closing as we have tested the fix on @lgayatri environment and reinstall seemed to fix the issue as per @javierfz1980

**Comment by SemperFu** [comment]
@jak-atx I just got this same issue today. I removed all my VHCs and the current ova and redeployed another one registering to vcenter. It's the same version. Do I need to remove and reinstall the plugin or run the upgrade script?
