### ISSUE TITLE
insecure registry is not getting configured when VCH is created

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-ui#430]
**VIC-UI version:**
VIC-1.3.1

If applicable: 

[In the VIC plugin] > Summary tab > Version

**Platform details:**
MAC

**Browser details:**
Chrome

**Additional details:**
"Insecure registry access" option in "Registry Access" tab is not getting added to the VCH. This can be confirmed from the vic-machine command line displayed in the end!

**Steps to reproduce:**
Create a VCH and configure insecure registry

**Actual behavior:**
In the vic-machine command in the end, there is NO --insecure-registry option

**Expected behavior:**
There should be --insecure-registry option

**Logs:**
N/A

See:

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.monitoring.doc/GUID-7E10C58F-16EA-44AB-8AA0-8D4A66399879.html

**Additional details as necessary:**

**Comment by jak-atx** [comment]
@javierfz1980 please verify if this is correctly being passed in the api request from the wizard.

@zjs can you confirm the '--insecure-registry option' is required in the cli command?

**Comment by javierfz1980** [comment]
I’m seeing the option in the CLI and also in the request on my local env, as you can see in the screenshots:

![insecure-registry-cli](https://user-images.githubusercontent.com/36636787/39151703-70ebb686-471c-11e8-8d2f-9c69da8275e1.png)
![insecure-registry-request](https://user-images.githubusercontent.com/36636787/39151704-712182f2-471c-11e8-956a-188c214a1998.png)

I'm testing against:
ova - vic-dev-v1.4.0-dev-4372-3f7dc144.ova
vic-ui - vic_17999.tar.gz (v1.3.1.1085)

Could you please provide the exact ova and ui versions ?

Thanks
