### ISSUE TITLE
Increasing the poll time to avoid timeouts with network intermittency on conditional waits 

### ISSUE THREAD

**Issue by lmalvins** [vmware/vic-ui#431]
Sometimes with network intermittency or delay, some elements aren't found when the poll time is over because the poll start over and over agin til the global time is over without find the element. Increasing the poll time, but don't the global time,  the poll would have more chance to find the element.

#For stories, please include the information below:

**User Statement:**

A brief statement describe who, what and why of the story for example - As a job seeker, I want to search for a job, so I can advance my career.

**Details:**
Any details of what you want that might clarify for the developer how to approach the implementation.

**Acceptance Criteria:**
Specific deliverable and actionable items that the story needs to deliver in order to be considered complete, the more detail here the more accurate the implementation will be.

#For bug reports, please include the information below:

**VIC-UI version:**

If applicable: 

[In the VIC plugin] > Summary tab > Version

**Platform details:**

Which platform are you using? (Windows, Mac OS, Linux, etc)

**Browser details:**

Which browser are you using? (IE, Chrome, Firefox, etc)

**Additional details:**

If applicable please include the following:

Error messages. (In the UI or from the browser's developer tools)

Request/response, including headers (from the browser's developer tools).

**Steps to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Logs:**

If applicable attach vsphere_client_virgo.log

See:

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.monitoring.doc/GUID-7E10C58F-16EA-44AB-8AA0-8D4A66399879.html

**Additional details as necessary:**

**Comment by jak-atx** [comment]
This has been merged
