### ISSUE TITLE
Add nightly test for DVS under a network folder

### ISSUE THREAD

**Issue by javierfz1980** [vmware/vic-ui#435]
**User Statement:**
Customers reported that in the Create VCH wizard they don't see port groups for switches they have in the VC inventory. Port groups that did not show up were under a network folder. 
This will be fixed by https://github.com/vmware/vic-ui/issues/389

Steps to reproduce:

Create a network folder in VC and create at least one distributed virtual switch, and add at least a host to it
Create two port groups for the switch
In the wizard try to create a VCH using the two port groups for bridge and client network respectively

Expected behavior:
User should be able to see and select the port groups

**Details:**
We need to create an e2e and add it to the nightly tests in order to validate the fix on #389

**Comment by jak-atx** [comment]
I think this may need to be taken up by the product qa team since they are now handling the different vc configurations and I think this would fall under this umbrella. @mdharamadas1 can you please confirm and/or advise how we should handle this one?

**Comment by mdharamadas1** [comment]
Looks like this will fit in the nightly test suite we have in `vic-product`, so I added it to that epic. Can we add more details around what kind of VC setup this needs?

**Comment by javierfz1980** [comment]
You can find all the information on the original issue: https://github.com/vmware/vic-ui/issues/389

**Comment by mdharamadas1** [comment]
@andrewtchin we missed planning this, so I assigned same points as any other nightly test to this.
