### ISSUE TITLE
Test flex vs 6.7

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-ui#452]
Some plugin customers have reported a critical issue with Flex Client 6.7GA: PR: 
https://bugzilla.eng.vmware.com/show_bug.cgi?id=2104626

Certain plugins which were not upgraded to be compatible with Spring 4 can trigger a Flex Client crash.

We need to thoroughly test the plugin against this scenario to make sure we don't see any issues.

**Comment by jak-atx** [comment]
We also need to test our previous released plugins from 1.0

**Comment by sgairo** [comment]
Address with documentation.
