### ISSUE TITLE
IP Range input is not selectable on VCH Creation Wizard

### ISSUE THREAD

**Issue by javierfz1980** [vmware/vic-ui#461]
**Details:**
During VCH Wizard creation, on Network step under advanced 'Advanced -> Optional Container Networks' the IP Range input is not selectable.

**Actual behavior:**
IP Range input is not selectable.

**Expected behavior:**
IP Range input should be selectable.

![input-disabled](https://user-images.githubusercontent.com/36636787/39582021-4e41c4dc-4ec3-11e8-91b7-88ab58104478.gif)

**Comment by jak-atx** [comment]
@mdubya66 @mhagen-vmware any input on a priority for this one?
