### ISSUE TITLE
Getting Started Page/fileserver updates for VIC UI plugin automated install

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-ui#465]
Related to PR: https://github.com/vmware/vic-product/pull/1790
**User Statement:**

As a user I want to be able to manage VIC UI plugin auto install.
 
**Details:**

**Acceptance Criteria:**
- [x] Add new modal which shows the fingerprint with a cancel and continue button
- [x] Add an ajax call to get the thumbprint from vcenter
- [x] Add call to the API for plugin install
- [x] UX review
- [x] Display success/error messages from auto install
- [x] Alert to restart services
- [x] Configure an automated environment ready for pipeline
- [x] Add unit tests

**Comment by morris-jason** [comment]
Changes to the vic-product repo should be made to the `feature/auto-vic-ui-plugin` branch.
