### ISSUE TITLE
Clusters nested within folders are not selectable in VCH creation wizard

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#468]
**VIC-UI version:**

1.3.1

**Platform details:**

N/A

**Browser details:**

N/A

**Steps to reproduce:**

Create a folder within a datacenter. Create a cluster within that folder.

![image](https://user-images.githubusercontent.com/408880/39771598-a8434432-52a7-11e8-94fb-1c1f42196d5b.png)

**Actual behavior:**

The cluster is not shown in the Creation wizard.

![image](https://user-images.githubusercontent.com/408880/39771626-b952fd76-52a7-11e8-94aa-a84b4f6c3718.png)

**Expected behavior:**

The cluster should be shown, nested within the folder (or folders).

**Additional details:**

If the cluster is removed from a folder, it is shown.

![image](https://user-images.githubusercontent.com/408880/39771699-f2da38a2-52a7-11e8-905b-b952cdccd1d7.png

**Logs:**

Not supplied.

bug#2130991

**Comment by mdubya66** [comment]
bug 2130991, needs an owner

**Comment by zhoumeina** [comment]
fixed by Javier
pr details:
https://github.com/vmware/vic-ui/pull/561

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-reported issue.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic-ui/releases/tag/v1.4.3
