### ISSUE TITLE
Design a way for the creation wizard to allow selection of non-VCH resource pools as compute resource

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#473]
**User Statement:**

As a VI Admin, I would like to create a VCH within a resource pool using the VCH creation wizard.

As a VI Admin, I do not want to see resource pools I cannot use, such as those belonging to another VCH.

**Details:**

To address this use case, the UI needs a way to get a list of non-VCH resource pools. This issue tracks that design work.

If necessary, this design may impose new requirements on the VCH list API.

**Comment by mdharamadas1** [comment]
Just design and doc

**Comment by javierfz1980** [comment]
This is fixed on #561

**Comment by renmaosheng** [comment]
thanks Javier for the confirmation.

**Comment by zjs** [comment]
I think this may be worth mentioning in the release notes, perhaps as a part of the release note for #468.

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic-ui/releases/tag/v1.4.3
