### ISSUE TITLE
Automated VIC UI Plugin - Update drone trigger

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-ui#489]
**User Statement:**
As a developer I want automated testing of the automated VIC UI plugin install.

**Details:**

**Acceptance Criteria:**
- [ ] Update vic-ui downstream triggers to vic-product instead of vic

**Comment by zjs** [comment]
@wjun: This should be an easy change to update the `DOWNSTREAM_REPO` variable in the `.drone.yml`:

https://github.com/vmware/vic-ui/blob/0b8d9678436032adac61303006a0363ecc345492/.drone.yml#L103-L116
