### ISSUE TITLE
VIC Shortcut on VCSA H5UI shows incorrect number of VCH and containers

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic-ui#49]
@lgayatri commented on [Tue Nov 14 2017](https://github.com/vmware/vic-product/issues/1076)

VIC 1.3: vic-dev-2419-v1.3.0-dev1-178-gfbdb6d5.ova
VCSA : 6.5U1 GA

![image](https://user-images.githubusercontent.com/25006749/32794130-fdce0944-c98d-11e7-9b11-86a73f69583a.png)

Inventory shown is incorrect, I have 50 VCHs and 2500 containers on this VCSA.

**Comment by jooskim** [comment]
Could you let me know what the vCenter setup is like (e.g. enhanced linked) and show the Cluster setup in the Hosts and Clusters view?

**Comment by lgayatri** [comment]
This is embedded VCSA . Filtered on VCH's name pattern U-VIC and you can 50 items being displayed here

![image](https://user-images.githubusercontent.com/25006749/33011878-3d753984-ce05-11e7-9cd1-0d7b1d61815c.png)

**Comment by andrewtchin** [comment]
resize after investigation is complete

**Comment by jooskim** [comment]
Started investigation by looking into this VC

**Comment by jooskim** [comment]
Something I'm fairly sure from the screenshot above is that the number of container VMs is incorrect because of the pagination filter is applied wrong in the VIC UI Java service. I will fix this first.

Also, looking into your VC @lgayatri , it seems that you have a bunch of Container VMs that are detached from their respective VCH resource pool. Could you explain how you ended up with that state?

**Comment by jooskim** [comment]
![image](https://user-images.githubusercontent.com/3834071/33637971-4f7e5954-d9e9-11e7-98c3-c172e2108ded.png)

@lgayatri Does this look right to you? I'm currently yet testing my fix on my dev environment so you should not be seeing the right # of VMs

**Comment by lgayatri** [comment]
@jooskim , Yes - the number of VCHs shown as 54 and the number of containers as 2660 are correct.

**Comment by jooskim** [comment]
Awesome. I'll get this in asap

**Comment by lgayatri** [comment]
Tested with vic-v1.3.0-rc3-2784-7d227d5c.ova

H5C UI shows correct inventory:
![image](https://user-images.githubusercontent.com/25006749/33762011-0b33e094-dc31-11e7-9ce7-97e1da7f9499.png)
