### ISSUE TITLE
Intermittent "Could not find any VIC appliance VM" error when using Linked Mode

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#501]
**VIC-UI version:**

1.4.0 GA

**Summary:**

Similar to what's described in #368, "Could not find any VIC appliance VM" errors are intermittently shown in a Linked Mode environment with 4 VCs.

**Steps to reproduce:**

Deploy a Linked Mode environment with 4 VCs. Deploy the 1.4.0 GA OVA. Configure the UI plugin. Attempt to use the plugin from within the H5 client.

**Actual behavior:**

Intermittently, a "Could not find any VIC appliance VM" error is displayed.

**Expected behavior:**

The UI plugin works consistently, even in Linked Mode.

**Logs:**

(requested)

**Additional details as necessary:**

In this environment, VCHs sometimes appear multiple times in the datagrid. If this is unrelated, we should file it as a separate issue.

**Comment by morris-jason** [comment]
Investigate the effects that https://github.com/vmware/vic-product/issues/1702 may have on this issue. Specifically, consider the effects from refactoring `configure.go` not to use the admiral rest client as a tag lookup mechanism.

**Comment by zhoumeina** [comment]
fixed by pr: #660
