### ISSUE TITLE
Check vic-ui with VC HA mode

### ISSUE THREAD

**Issue by lmalvins** [vmware/vic-ui#506]
Ensure that vic-plugin works after HA the VIC appliance as well, see bugzilla:
2127492

**Comment by renmaosheng** [comment]
Lu, could you please help Meina on this? thanks.

**Comment by luwang-vmware** [comment]
@renmaosheng  I deployed and enabled VCHA(with basic mode) within vsphere6.7 build. VIC plugin can be successfully installed and VCH can be deployed through VIC plugin.
I also trigger VC failover and check that the VIC plugin works well in the new active VC and VIC appliance is accessible as well.

Thanks,
Lu

**Comment by luwang-vmware** [comment]
Close it per the previous comment.
