### ISSUE TITLE
Refactor of Compute Capacity - Resource Tree Selector

### ISSUE THREAD

**Issue by javierfz1980** [vmware/vic-ui#514]
We need to do a deep refactor on the Compute Capacity resource tree selector in order to achieve the functionalities requested in the following issues:

1- Design a way for the creation wizard to allow selection of non-VCH resource pools as compute resource #473 
2- Clusters nested within folders are not selectable in VCH creation wizard #468 

The current tree selector by design is showing only clusters and stand alone hosts. We need to do several changes on the core of the component in order to also display compute resources and folders (cluster within folders)

**Comment by renmaosheng** [comment]
@zhoumeina could you please close this if all code are merged and tested? thanks.
