### ISSUE TITLE
UI Install Scripts fails with password that has a space

### ISSUE THREAD

**Issue by artbird309** [vmware/vic-ui#526]
**VIC-UI version:** 1.4

**Platform details:** Installing from VCSA

**Additional details:**

When I was running the VCSA UI plugin install script I was getting the error message that it would not be install and "--company must be specified". I tried to run the uninstall script and it gave a error that I was passing invalid parameters which it listed as being the last half of my password after a space.

I then created a new administrator user that had no spaces in it and tried again to install and it worked just fine.

**Comment by zjs** [comment]
Thank you for the bug report, @artbird309 (and sorry about the delay in getting this triaged).

**Comment by zjs** [comment]
I think this is worth a release note, as it was a customer-reported issue.
