### ISSUE TITLE
VIC plugin throws a parsing error when customer tries to specify only the gateway for management network.

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#568]
@yeshwantbabar commented on [Thu Mar 29 2018](https://github.com/vmware/vic/issues/7602)

![screen shot 2018-03-22 at 12 53 13 pm](https://user-images.githubusercontent.com/33335970/38094979-e2201a46-3334-11e8-9779-7689b6a9c241.png)
When you provide a gateway for the management network, it's mandatory to provide at least one routing destination. UI Plugin doesn't reflect that. It has two separate fields for Gateway and Routing destinations. If the customer doesn't provide both the fields properly, plugin throws a weird parsing error [Refer to the screenshot]. 

There should be just one text field, Routing Destinations:Gateway along with a tooltip/help which explains this configuration. 

The same thing applies to client network configurations as well. 

---

@mdubya66 commented on [Fri Jun 22 2018](https://github.com/vmware/vic/issues/7602#issuecomment-380188437)

is there a workaround for this and if so let's document and lower to a p2

---

@AngieCris commented on [Fri Jun 22 2018](https://github.com/vmware/vic/issues/7602#issuecomment-380203427)

@jak-atx It rather looks like an enhancement than a bug - we should provide more helpful message instead of parsing error. We do have this requirement in the documentation that routing destination must be provided if there's a gateway. 

---

@stuclem commented on [Tue May 15 2018](https://github.com/vmware/vic/issues/7602#issuecomment-389189418)

Proposed release note:

- <b>Create Virtual Container Host wizard plugin throws a parsing error when you specify only the gateway for the management or client networks. [#7602](https://github.com/vmware/vic/issues/7602)</b><br>When you provide a gateway for the management or client network, it is mandatory to provide at least one routing destination. The Create Virtual Container Host wizard does not conform to this behavior and has two separate fields for the Gateway and Routing destinations. If you do not fill in both the fields correctly, the wizard reports a parsing error.

I added this in both the `vic` and `vic-ui` release notes.

---

@zjs commented on [Tue May 22 2018](https://github.com/vmware/vic/issues/7602#issuecomment-391155895)

From discussion with @pdaigle: Management network should be restructured to make it clearer that the when a gateway is entered, one or more routing destinations must be entered. Client-side validation should be added to enforce this. This will be more consistent with the CLI.

**Comment by lweitzman** [comment]
Updated mockups to show "Routing destination:Gateway" and relabeled hint text for static IP to be "IP range or CIDR" 
https://vmware.invisionapp.com/share/MUD5FRBS8#/239666112_Create_VCH_Wizard_-_5_Network_Simple_3

![screen shot 2018-08-03 at 9 05 31 am](https://user-images.githubusercontent.com/626032/43644339-660179c4-96fc-11e8-9fee-29a86a475a01.png)

**Comment by stuclem** [comment]
UI change, so doc needs to be updated accordingly.

**Comment by zhoumeina** [comment]
@zjs ,I noticed before "Routing destination" is not required field, so now, both Gateway and Routing destination are required. Right?

**Comment by zhoumeina** [comment]
clarity
![image](https://user-images.githubusercontent.com/4946616/44844105-8c9fb880-ac7c-11e8-8086-ad27fa380b40.png)

**Comment by zhoumeina** [comment]
I also update the tooltips to make it more clear for users. 
For example: 
Routing destination: 
IP addresses are not valid,please input one or more routing destinations in a comma separated list, e.g. 10.1.0.0/16,10.2.0.0/16:10.0.0.1

**Comment by zhoumeina** [comment]
fixed by pr:#583

**Comment by zjs** [comment]
Despite being a customer-reported issue, this does not seem significant enough to mention in the release notes.

**Comment by zjs** [comment]
I think this is worth a release note, as it fixes a previously release noted issue: https://github.com/vmware/vic/issues/7602#issuecomment-389189418

**Comment by stuclem** [comment]
Added as a resolved issue in https://github.com/vmware/vic/releases/v1.4.3
