### ISSUE TITLE
Determine when the Flex client plugin was last functional with vSphere 6.5

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#570]
There has been a report that the 1.4.3 Flex client plugin is not functional with vSphere 6.5+.

It is not currently known whether this is a regression, but the documentation suggests that it may be. We should investigate what versions of the Flex client plugin have worked with vSphere 6.5 in order to decide how to proceed.

The Flex client plugin provides substantially less functionality than the H5 client plugin, and the H5 client is the clear priority going forward. If the Flex client plugin has not been functional with vSphere 6.5 since at least 1.4.0, we may be able to safely choose not to attempt to install/upgrade it with vSphere 6.5 as a part of the 1.4.3 UI plugin installation automation. However, if it has worked for previous releases of 1.4.x we should continue to support it to avoid removing functionality in a patch release.

Possibly related:
 * #452 
 * #563
 * https://github.com/vmware/vic-product/pull/1779#discussion_r190959608

**Comment by renmaosheng** [comment]
Tested vic 1.4.0 with vsphere 6.5 (6.5.0.20000 - build number: 8815520), the flex client plugin is not shown up. the html5 works properly. so there is no regression from 1.4.3 build. We should consider refactor the code to not support flex in 1.5.

**Comment by zjs** [comment]
It seems like https://github.com/vmware/vic-ui/issues/570#issuecomment-417183187 covers the investigation. It looks like #604 has been filed for tracking the resolution of this.
