### ISSUE TITLE
After disabling and re-enabling use of client certificates, no option to select certificates is shown

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#576]
**VIC-UI version:**

1.4.2 GA

**Steps to reproduce:**

Load the VCH Creation Wizard. Proceed to the "Security" page.

1. Disable use of client certificates.
2. Enable use of client certificates.

**Actual behavior:**

No option to select certificates is shown.

**Expected behavior:**

The option to select certificates re-appears.

**Screenshots:**

#### Before
![step 5 - original](https://user-images.githubusercontent.com/408880/44535600-f411b180-a72c-11e8-90d8-35c24560e9f2.png)

#### After
![step 5 - after radiobutton actioned twice](https://user-images.githubusercontent.com/408880/44535598-f3791b00-a72c-11e8-969b-0e1df2df6263.png)

bug2185779

**Comment by zhoumeina** [comment]
AlertIconAndTypesService  has been deprecated in latest version in 0.11 So there will be a javascript error after swith the button.

**Comment by zhoumeina** [comment]
fixed by pr#589

**Comment by zjs** [comment]
Despite being a customer-reported issue, this does not seem significant enough to mention in the release notes.
