### ISSUE TITLE
Display the VCH Management API version on plugin summary page

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#586]
As described in vmware/vic-product#1952, display the version of the VCH Management API the plugin is communicating with on the plugin's "summary" page, near where the plugin version is displayed.

As the user is not able to select which API server to use (#572), providing this information may greatly aid debugging when multiple versions of API servers are available.

**Comment by zhoumeina** [comment]
@zjs, Do you mean the version of this api: https://10.193.25.225/ui/vic/rest/services/get-vic-appliances

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/44964195-bfd69600-af61-11e8-88a6-03cc520eb005.png)

**Comment by zjs** [comment]
> Do you mean the version of this api: https://10.193.25.225/ui/vic/rest/services/get-vic-appliances

I'm not sure where that API sources its data from. If it's from the metadata on the VM, I worry that there are cases where it might be inaccurate.

I think the safest way to get the API server version is from the API server itself (from the `/version` API endpoint).

The code would be equivalent to this, but would call `/container/version` instead of `/container/hello`:

https://github.com/vmware/vic-ui/blob/3a0295a40780f47de01755468ae7f38286e205d9/h5c/vic/src/vic-webapp/src/app/create-vch-wizard/create-vch-wizard.service.ts#L573-L601

I suspect there's a simple refactoring that would avoid duplication between `verifyVicMachineApiEndpoint` and the new method (`getVicApplianceVersion`?).

> VIC Appliance Version

Strictly speaking, this is the VCH Management API endpoint version. The VIC OVA (aka VIC Appliance) actually has a separate version number.

**Comment by zjs** [comment]
Marking as need info: we need to confirm whether this is required for 1.4.3.

**Comment by zhoumeina** [comment]
fixed by:#598
