### ISSUE TITLE
Add signpost text explaining the implications of the base image size

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#59]
The text below the input warning the user that the value cannot be changed is helpful. Adding signpost text to explain the purpose of the value may further assist users.

Again, explaining this in terms familiar to a VI Admin may be valuable.

Additionally, it may be helpful to clarify that the setting is the base _container VM_ image size.

**Comment by pescerosso** [comment]
Since in a previous step we call out "container VM", we also here say "container VM base image size"

**Comment by zjs** [comment]
This is a very low priority, but could be included in the release if it is a simple text change that can be made without sacrificing something else.

**Comment by lweitzman** [comment]
I suggest this: "The size of the base image from which to create other images. Typically you don’t need to change this since images are thin-provisioned and do not usually consume 8GB of space." @hickeng @zjs thoughts?

**Comment by stuclem** [comment]
@cristianfalcon: "The size of the base image from which to create other images. You do not normally need to change this value. The default size is 8GB, but images are thin-provisioned so they do not usually consume 8GB of space."
