### ISSUE TITLE
Can not select a datacenter as compute resource

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic-ui#596]
**User Statement:**

As a vic admin, I want to select a datacenter as compute resource when I create a VCH from webclient.

**Details:**
See the screenshot,  I can not select the datacenter as compute resource to create a VCH.

**Acceptance Criteria:**
datacenter is selectable in compute capacity step of VCH creation wizard

**VIC-UI version:**
v1.4.3-rc1
![create vch](https://user-images.githubusercontent.com/1393804/45404813-0aa78a80-b693-11e8-8bd0-871be83927ea.png)

**Comment by zjs** [comment]
The failing test seems to target a standalone host (i.e., a host not in a cluster), not a datacenter directly: https://github.com/vmware/vic-product/blob/7d7bbb3eeee9de6e30fb0e67377d58a2b03292c0/tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot#L72

**Comment by zhoumeina** [comment]
not a issue. close it.

**Comment by DanielXiao** [comment]
There are 3 ESXi servers under the datacenter, see screenshot:
<img width="564" alt="screen shot 2018-09-13 at 3 50 16 pm" src="https://user-images.githubusercontent.com/1393804/45474710-00f25580-b76d-11e8-94ed-52a82c2c8ca2.png">

But in the "Create Virtual Container Host" wizard, none of them is show as compute resource and user is blocked in this step.
<img width="1039" alt="screen shot 2018-09-13 at 3 54 30 pm" src="https://user-images.githubusercontent.com/1393804/45474851-562e6700-b76d-11e8-9ebf-61746561cf63.png">

**Comment by DanielXiao** [comment]
Acceptance Criteria:
ESXi server is showing and selectable in compute capacity step of create VCH wizard

**Comment by renmaosheng** [comment]
https://github.com/vmware/vic-ui/pull/603 fixing this.
