### ISSUE TITLE
Add signpost text to the bridge network settings that explicitly notes this should be an isolated L2 broadcast domain

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#60]
Additionally, we could say that it should be a VXLAN or should be configured with a VLAN ID.

**Comment by zjs** [comment]
This is a very low priority, but could be included in the release if it is a simple text change that can be made without sacrificing something else.

**Comment by lweitzman** [comment]
I suggest: "Bridge networks are the network or networks that container VMs use to communicate with each other. Every virtual container host (VCH) must have a unique bridge network. Do not use the bridge network for any other VM workloads, or as a bridge for more than one VCH." 
@pdaigle @hickeng @zjs

**Comment by stuclem** [comment]
@cristianfalcone, the proposed text from @lweitzman looks good to me.
