### ISSUE TITLE
Flex plugin cannot show in vCenter web client on 6.5/6.7

### ISSUE THREAD

**Issue by wjun** [vmware/vic-ui#604]
Since VIC 1.4.0, Flex plugin cannot show in vCenter web client on 6.5/6.7 after installation.

We will either fix the issue or decide not continue to support Flex plugin.

**Comment by zhoumeina** [comment]
We decided not support flex plugin anymore. @wjun , we can check it with Steven.

**Comment by renmaosheng** [comment]
Meina，
      this bug is tracking the effort to remove the flex code for VIC 1.5.

**Comment by renmaosheng** [comment]
Meina,
      is this something we plan to fix in 1.5? if not, please move to 1.5.1, thanks.

**Comment by zhoumeina** [comment]
I will try to make a pr to remove flex and see if it can pass the CI. I am not sure how much effort we need to make CI pass.

**Comment by renmaosheng** [comment]
We also need to remove the flex plugin registering code, Wending will handle it.
