### ISSUE TITLE
Tree nodes are not consistent with vCenter view

### ISSUE THREAD

**Issue by wjun** [vmware/vic-ui#605]
When I create a VCH from UI plugin wizard, during the step of selecting a computing resource, in two cases, UI plugin shows the tree nodes structure in different order than vCenter view.

Case 1: there are 3 clusters under a datacenter: cls1, cls2, cls3. The tree node list order is cls3, cls2, cls1, while vCenter view is cls1, cls2, cls3.

Case 2: there are 3 datacenters dc1, dc2, dc3. dc2 and dc3 has no cluster but a single ESXi host, dc1 has a cluster. The tree node list order is dc2, dc3, dc1, while vCenter view is dc1, dc2, dc3.

**Comment by zhoumeina** [comment]
After investigation, I found that this api returns different order with host view. 
https://localhost:9443/ui/vic/rest/data/properties/urn:vmomi:Datacenter:datacenter-2:c6c0457c-f1dd-4fe8-865c-fa6362d423fe?properties=host,cluster

**Comment by zhoumeina** [comment]
According to QueryUtil.java line 332:
 response  = dataService.getData(requestSpec);
I debugged into the result. This order is returned by this service. However, this service is provided by vsphere-sdk. 
![image](https://user-images.githubusercontent.com/4946616/46931965-17e3da80-d080-11e8-8704-6c41a30bd49d.png)

**Comment by zhoumeina** [comment]
fixed by :#613
