### ISSUE TITLE
VCH creation using Client failing with " parsing vch body from "" failed, because json: cannot unmarshal object into Go struct field Network.static of type models.CIDR"

### ISSUE THREAD

**Issue by KeithRichardLee** [vmware/vic-ui#606]
**VIC-UI version:**
v1.4.1.1262

**Platform details:**
Windows Server 2012 R2

**Browser details:**
FireFox 60.2 ESR

**Additional details:**
Fresh install of VIC

**Steps to reproduce:**
Create a VCH in the vSphere Client using following parameters taken from the vic-machine command

./vic-machine-linux create --name VCH_01 --compute-resource /SA-Datacenter/host/SA-Compute --image-store SA-Shared-01-Remote/VCH_01_IDS --base-image-size 8GB --volume-store SA-Shared-01-Remote/VCH_01_VDS:default --bridge-network pg-Bridge --bridge-network-range 172.16.0.0/12 --public-network pg-Public --public-network-ip 192.168.0.97/24 --public-network-gateway 192.168.0.10 --dns-server 172.20.10.10 --client-network pg-Clients --client-network-ip 10.2.10.97/24 --client-network-gateway 172.20.10.10/24:10.2.10.10 --management-network pg-SA-Management --management-network-ip 172.20.10.97/24 --management-network-gateway 172.20.10.10/24:172.20.10.10 --container-network pg-Containers:container-nw --container-network-ip-range pg-Containers:10.1.10.100-10.1.10.200 **--container-network-gateway pg-Containers:10.1.10.10/24** --container-network-dns pg-Containers:10.1.10.10 --container-network-firewall pg-Containers:published --tls-cname VCH_01 --certificate-key-size 2048 --no-tlsverify --user Administrator@VSPHERE.LOCAL --thumbprint AE:22:9A:DC:83:01:A3:27:F6:31:16:44:99:F9:C3:60:66:19:56:25 --target sa-vcsa-01.vclass.local/SA-Datacenter --registry-ca ca.crt --ops-user administrator@vsphere.local

Note: the UI does not create --container-network-gateway in CIDR format. I have manually added /24 to it. I will open a separate issue for this.

**Actual behavior:**
Following error thrown
parsing vch body from "" failed, because json: cannot unmarshal object into Go struct field Network.static of type models.CIDR

![screen shot 2018-09-18 at 11 07 02](https://user-images.githubusercontent.com/41379304/45680685-70809000-bb33-11e8-8796-be2104d8a9fa.png)

**Expected behavior:**
Successfully creates VCH or provide a more meaningful answer if there is a legitimate error.

**Logs:**
No entries in vsphere_client_virgo.log at time of attempted creation. 

**Additional Info:**
Running above vic-machine command, which was generated by the wizard (after /24 is added to --container-network-gateway), is successful.

**Comment by renmaosheng** [comment]
Hi Keith,
      Thanks for reporting the issue. 
Meina,
       could you please take a look? thanks

**Comment by zhoumeina** [comment]
I will take care of this.

**Comment by patschi** [comment]
I've just set up a fresh VIC 1.4.4 and experienced same issue. So I'm right that this fix haven't been released with 1.4.4 yet?

**Comment by zhoumeina** [comment]
@patschi , container-network-gateway already changed to CIDR format in release 1.4.4. Please refer this pr: https://github.com/vmware/vic-ui/pull/619/files

**Comment by farflungfish** [comment]
Hello I have experienced this same bug today on version vic-v1.4.4-6375-0a6da3d4.ova

Is there anything I can provide to you which you can use to replicate the problem?

**Comment by dukesrg** [comment]
Problem still exists with 1.5.0.1462 official relese plugin
