### ISSUE TITLE
Generated CLI in wizard has incorrect construction for multiple dns servers and compute resource

### ISSUE THREAD

**Issue by hickeng** [vmware/vic-ui#610]
In 1.4.3 there are two issues observed with the generated command line:
1. The `--compute-resource-name` option name should be `--compute-resource`
2. If specifying multiple DNS servers, the additional servers are missing the `--dns-server` option name, resulting in misaligned processing of following argument.

I've marked this as sev3 because it's was difficult for _me_ to determine what was wrong with the command line, until I broken it down into individual components. For a customer who doesn't know what it _should_ be I don't see how they could fix it easily.

**Comment by zhoumeina** [comment]
fixed by pr:#612
