### ISSUE TITLE
Ensure the "?" buttons link somewhere

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#62]
Currently, the buttons seem to be non-functional.

**Comment by stuclem** [comment]
@mdubya66 are we removing the `?` help links in 1.3?

**Comment by stuclem** [comment]
@cristianfalcone I will provide the correct links for the ? links in this issue.

**Comment by stuclem** [comment]
@cristianfalcone here are the links for the ? buttons on the different pages of the VCH deployment wizard:

- General Settings: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_general_settings.html
- Compute Capacity: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_compute.html
- Storage Capacity: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_storage.html
- Networks: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_networking.html
- Security: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_security.html
- Operations User: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/set_up_ops_user.html

The first two links are not live yet, as sometimes it takes a while for docs to go live after I merge them to vmware/gh-pages, but the URLs should be good. The other URLs are live. The content of the pages is not yet final, but the links are the ones that we should use.

If you need more links, please let me know.

Thanks!

**Comment by stuclem** [comment]
All links are now live

**Comment by cristianfalcone** [comment]
Thanks @stuclem, adding them now.

**Comment by zjs** [comment]
Unless the fix becomes risky or complex, it should be included in 1.3.0. However, we should not hold the release for this.
