### ISSUE TITLE
Review the validation logic in vic-ui

### ISSUE THREAD

**Issue by zhoumeina** [vmware/vic-ui#635]
The current validation will hash the whole certificate chain resulting in the wrong thumbprint. https://github.com/vmware/vic-ui/blob/master/h5c/vic-service/src/main/java/com/vmware/utils/ssl/ThumbprintTrustManager.java#L43

Look into validating certificates in a way that can better handle chains. 

Might be possible to use KeyStore to validate the certificate against the web client's java keystore and drop thumbprint validation all together. 
https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html

Doing this this will greatly reduce one of the highest drivers for support cases relating to certificate thumbprint miss matches when the customer has replaced their vCenter certificate using a chain certificate.

**Comment by renmaosheng** [comment]
It requires lots of engineering work to refactor the code to support, moving to 1.5.1.  Thanks.

**Comment by renmaosheng** [comment]
@zhoumeina do we still have work to do for this issue? thanks.

**Comment by renmaosheng** [comment]
haven't hit any issue since last fix.
