### ISSUE TITLE
Update links in UI plugin to point to 1.5 docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#636]
All of the doc links in the vSphere Client plug-in for VIC 1.5 need to point to the 1.5 version of the docs. 

I have posted a placeholder version of the 1.5 docs at https://vmware.github.io/vic-product/assets/files/html/1.5/.

@renmaosheng can you please assign this accordingly?

**Comment by zhoumeina** [comment]
ok. I will take a look.

**Comment by stuclem** [comment]
Thanks @zhoumeina

**Comment by zhoumeina** [comment]
fixed by: #637
