### ISSUE TITLE
Help link in Registry Access page points to incorrect doc page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#639]
Found in vic-dev-v1.5.0-dev1-6662-560b4cda.ova.

Click on the help button in the Registry Access page of the Create VCH wizard:

![registry-link.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/7971d716-77c8-4d57-beb0-b2a226e121b3)

This button opens https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_security.html. It should open https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_registry.html.

I have only just spotted in 1.5, but this might be an issue in previous releases too.

**Comment by zhoumeina** [comment]
@stuclem , yes. I submit another fix for this. #649

**Comment by stuclem** [comment]
Thanks @zhoumeina. All looks good now!
