### ISSUE TITLE
Update help link to network requirements

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-ui#647]
I have reordered the docs somewhat for 1.5, and have grouped all networking requirements into a single page. 

Currently, we have two help buttons in the Configure Networks page of the Create VCH wizard:

- One general help buttton (the ? button at the top)
- One VIEW NETWORK REQUIREMENTS button.

These currently both point to https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_networking.html.

Would it be possible to change the VIEW NETWORK REQUIREMENTS button to point to the new page, https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/network_reqs.html? The general help button at the top can stay as it is. 

![networkreqs.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/1ee3b2f4-8fff-4225-9261-71bc619cb264)

Thanks!

**Comment by renmaosheng** [comment]
@zhoumeina could we change this?

**Comment by zhoumeina** [comment]
fixed by pr:#648
