### ISSUE TITLE
VIC 1.4.4 H5 plugin is not being installed (install UI plugin radio button) during VIC registration with VC 6.7 U2 

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-ui#652]
Bug Report Basic Information
REQUIRED:

vCenter Server version: 6.7 U2
vCenterBuild: 10882746
Embedded or external PSC: No
Filename of the OVA you deployed: vic-v1.4.4-6375-0a6da3d4
How was the OVA deployed? Ovftool
Does the VIC appliance receive configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Initialization/Registration Stage

Bug Details:
VIC H5 plugin does not get installed on the VC even though the radio button "Install UI plugin" was selected in the VIC to VC registration wizard.

@lgayatri @renmaosheng @reasonerjt @anishmehta1

**Comment by zhoumeina** [comment]
fixed by pr:#659
