### ISSUE TITLE
In the containers tab of the VIC 1.5.3 RC3 UI plugin, when the next page button is clicked, the tab refreshes into the same page and the next page arrow disappears

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-ui#675]
vCenter Server version: 6.5 p03
Embedded or external PSC: No
Filename of the OVAs you deployed: vic-v1.5.3-rc3-7486-30200689.ova
How was the OVA deployed? ovftool
Does the VIC appliance receive configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application

- 40 VCH s deployed with 60 containers in each VCH resource pool (total: 2400)

When the next page arrow button is clicked in the containers tab of the VIC UI plugin, tab refreshes and next arrow button disappears and also unable to scroll down
Browser Used: google Chrome Version 75.0.3770.90 (Official Build) (64-bit)

Before clicking on next page arrow button (Watch bottom right):
![VIC_UI_1](https://user-images.githubusercontent.com/42163572/59665949-8362e680-91d1-11e9-8eef-8871c81e3e2b.JPG)

After clicking next arrow  (Watch bottom right):
![VIC_UI_2](https://user-images.githubusercontent.com/42163572/59665958-865dd700-91d1-11e9-9795-9635f7b32de6.JPG)

Does not allow to scroll down either

**Comment by zhoumeina** [comment]
fixed by pr: https://github.com/vmware/vic-ui/pull/676/files
