### ISSUE TITLE
Summary details can not display after clicking vsphere integrated container button in the vsphere 7.0

### ISSUE THREAD

**Issue by ading007** [vmware/vic-ui#679]
repro steps:
  1. click icon button as follow:
![image](https://user-images.githubusercontent.com/19757922/67256263-afacad80-f4b8-11e9-83cd-cf031af6efd8.png)
  
  2. jump to vic ui summary page as follow:
  
![image](https://user-images.githubusercontent.com/19757922/67256377-411c1f80-f4b9-11e9-92ea-f305c69fcf64.png)
  3. summary page can not display.

**Comment by renmaosheng** [comment]
could you please close the bug if this is confirmed to be fixed. thanks.

**Comment by zhoumeina** [comment]
This issue is fixed by vc team.
