### ISSUE TITLE
Re-organize the networking tab

### ISSUE THREAD

**Issue by zjs** [vmware/vic-ui#70]
Public/Bridge/Management/Client networks and proxy settings are for the Endpoint VM (i.e., the VCH itself), but the Container Networks are for the Container VMs. However, the container network settings are placed between the other two, making it unclear which settings are used by each entity.

Additionally, things with the same label might not actually be the same; "Static" for a network on the VCH is for the (single) address to assign to the Endpoint VM, but "Static" for a Container Network is actually an IP _range_ that the VCH will assign to the Container VMs it creates.

Match the compute configuration, where there are sub-sections for container settings and endpoint settings.

**Comment by lweitzman** [comment]
Here is a first pass at a reorganization of the networks across 2 images, the second scrolled down the page. 
![screen shot 2017-11-17 at 9 24 58 am](https://user-images.githubusercontent.com/626032/32951894-83d949bc-cb79-11e7-8912-1f3fe7fbac64.png)
![screen shot 2017-11-17 at 9 25 18 am](https://user-images.githubusercontent.com/626032/32951902-87594e0c-cb79-11e7-8c4f-00ab2fcce3b7.png)
