### ISSUE TITLE
the hotspot for the create vch wizard is shifted up

### ISSUE THREAD

**Issue by lweitzman** [vmware/vic-ui#80]
When trying to click on "+ New Virtual Container Host" the hot spot is shift above the text itself. its discoverable but not a good experience. this occurs in firefox.

![screen shot 2017-11-17 at 1 50 58 pm](https://user-images.githubusercontent.com/626032/32963684-c9cef7bc-cb9e-11e7-9df3-e8121133390e.png)

**Comment by jak-atx** [comment]
<img width="964" alt="firefox" src="https://user-images.githubusercontent.com/15793168/33623362-54de3e7e-d9b6-11e7-84a0-602b18c95122.png">

Louis, can you check if you are able to still reproduce this issue? I am not able to on mac firefox (as seen in this screen capture). If you are able to, please include the OS info as well as FF version info. Thanks.

**Comment by jak-atx** [comment]
Closing as non-reproducible. If this comes up again will re-open.
